### ISSUE TITLE
提问问题，这个候选的辅助码提示问题

### ISSUE THREAD

**Issue by verve91** [gaboolic/rime-shuangpin-fuzhuma#1]
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/62169380/e184092c-6715-4885-b03d-dfd00f852626)
就比如这个，我刚开始用的时候也是有这个提示的，就很想给他关了，现在不知道咋的他确实关了，我又想让他打开了，可我不会，不知道从那找，下面是我现在的样子
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/62169380/518aa600-365e-4295-b812-69157427b484)
有没有可能我这个是皮肤的问题，导致不现实的，我找不到原因了。
我换了个皮肤，也不显示，这次真的不知道为啥了
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/62169380/e62a262c-b62f-4bb0-86b8-f3b31b4e60e2)
可以看出来他后面是有空位的，但就是不显示
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/62169380/b532168e-28e0-4895-8f05-b010e780c5e7)

**Comment by verve91** [comment]
已解决

**Comment by gaboolic** [comment]
解决了就好 我记得注释里有开关辅助码提示
