### ISSUE TITLE
請問要怎麼批次把 【繁體中文字】 轉成 【小鶴雙拼（碼）】

### ISSUE THREAD

**Issue by trevim99** [gaboolic/rime-shuangpin-fuzhuma#103]
謝謝 gaboolic大神開發輔助碼方案🙏

我想把小鶴雙拼（碼） 加上 我之前慣用的嘸蝦米（碼表檔），也做成輔助碼（8105.dict.yaml）的碼錶形式。

請問要怎麼把嘸蝦米（碼表檔）里的 【繁體中文字】 轉成 【小鶴雙拼（碼）】？ 多謝指點。  👍

謝謝

例如：
敢 gj
設 ue
護 hu

嘸蝦米（碼表檔）的示例如下 ：

irp 敢
irph 憨
irrj 譁
irrq 譁
irrr 讘
irss 誹
iru 設
iru 諏
iruv 諏
irv 誡
irvu 護
irxo 諾
irz 譏
is 謊
isa 謝
isb 誅
isi 訓
isi 誙
isiv 誙

https://github.com/chinese-opendesktop/cin-tables/blob/master/boshiamy.cin

![image](https://github.com/user-attachments/assets/c02c8520-7b76-40f3-9968-594cfa99bff0)

**Comment by gaboolic** [comment]
小鹤音形只支持简体8000个字，没有繁体字
没太明白你的意思，你是想 前面2个码用双拼，后面两个码用嘸蝦米的前两个码吗？
这样的话，你可以参考五笔的方式

**Comment by gaboolic** [comment]
我有一个方案是 前面两码双拼 后面两码用五笔的前两码

**Comment by trevim99** [comment]
> 小鹤音形只支持简体8000个字，没有繁体字 没太明白你的意思，你是想 前面2个码用双拼，后面两个码用嘸蝦米的前两个码吗？ 这样的话，你可以参考五笔的方式

多謝回覆。
你是想 前面2个码用双拼，后面两个码用嘸蝦米的前两个码吗？ 》 是的。我已經初步測試過 ， 用您配制的【 墨奇音形 + 小鶴雙拼 】方案的演算規則可行。 所以我要 增加一個自定義的碼表內容：【前面2个码用双拼，后面两个码用嘸蝦米的前两个码】的碼表。 加這個碼表的用意是有時同音字太多候選字時，我可以快速打出來。
附圖是測試的圖， 1866行的   隔 （小鶴雙拼碼 ge，嘸蝦米（全碼beot）頭尾碼 bt ，如果隔的同音字太多時， 我只要打 geb ，就可以選到 【隔】了。

我只要能把 中文字（繁體/簡體都可以）批次轉成 小鶴雙拼碼，我應該能自己組合出 【前面2个码用双拼，后面两个码用嘸蝦米的前两个码】的碼表。謝謝


![image](https://github.com/user-attachments/assets/be28a0ea-c9a8-42d3-9da3-9896b33b7adc)


![image](https://github.com/user-attachments/assets/ba76b366-3df5-4709-8e15-3eebf8913989)

**Comment by gaboolic** [comment]
可以使用program/deal_ice_dict_to_moqi_xh.py脚本
```
with open('./opencc/moqi_chaifen.txt', 'r', encoding='utf-8') as dict_file:
    for line in dict_file:
        if "\t" in line:
            character, encoding, chaifen = line.strip().split('\t')
            if "'" not in encoding:
                
                # if character in '去我而人他有是出哦配啊算的非个和就可了在小从这吧你吗':
                #     encoding = encoding[0] + encoding[1].upper()
                if character not in dict_data:
                    dict_data[character] = encoding
```

这一段你改成open 无虾米的码表，encoding处理成无虾米的首末码就行了
