### ISSUE TITLE
手动排序/自动排序

### ISSUE THREAD

**Issue by valuex** [gaboolic/rime-shuangpin-fuzhuma#105]
感谢开发的功能，已经非常好用了。
能否再增加下功能，支持通过快捷键手动调整字符位置，或者在第二次输入时自动将已经选中的词置顶。

**Comment by gaboolic** [comment]
那就打开用户词库？

**Comment by gaboolic** [comment]
还是说在尽量固定词频的情况下 可以手动调序

**Comment by valuex** [comment]
具体说有两个：
1，用户输入某个词组后，下次输入自动置顶，比如输入“moqi”并“墨奇”后上屏后，下次再输入“moqi”，第一个候选项就是“墨奇”
2. 允许用户将当前“激活”的候选项通过快捷键或者鼠标右键置顶或前移。

**Comment by gaboolic** [comment]
第一个 打开用户词库就可以
第二个 rime没这个功能 也许用lua能搞
