### ISSUE TITLE
你好，英文单词输入，能否支持在英文模式下输入呢

### ISSUE THREAD

**Issue by xqhjay** [gaboolic/rime-shuangpin-fuzhuma#106]
就是在 ascii_mode 为英文模式时，输入英文不直接上屏，而是会作为输入码，对接英文单词翻译器呢？

**Comment by gaboolic** [comment]
其实是可以的，只是现在easy_en没有作为独立的输入方案
你在default.yaml里面加上easy_en
然后选择easy_en 即可

**Comment by xqhjay** [comment]
> 其实是可以的，只是现在easy_en没有作为独立的输入方案
> 你在default.yaml里面加上easy_en
> 然后选择easy_en 即可
> 

直接加上好像不行吧？英文模式下，不需要配置 lua processor 来接收按键吗？不然还是会直接上屏吧？

参考: https://github.com/shewer/rime-english

可以移植过来

**Comment by gaboolic** [comment]
![image](https://github.com/user-attachments/assets/32f4aff4-d93b-4a59-8eee-4d09ec310c6f)

**Comment by gaboolic** [comment]
![image](https://github.com/user-attachments/assets/0c8f1531-46e9-4acd-9adf-8af6e1cf452e)

**Comment by gaboolic** [comment]
可以的

**Comment by gaboolic** [comment]
直接加就行
