### ISSUE TITLE
1.0.1.2 的 `rime-moqi-wanxiang-schemas.zip` 词频不正常

### ISSUE THREAD

**Issue by CarameowCookie** [gaboolic/rime-shuangpin-fuzhuma#107]
具体表现为，许多本应该排在后面的生僻字或者繁体字，现在排到了前几页。

最极端的例子是「gy」，第 1 候选项是并不常用的「丨」。
![image](https://github.com/user-attachments/assets/44097941-876d-409b-ad57-2712e192dea7)

又如，输入「ve」，第 5 候选项是本应排在简体字后面的繁体字「這」
![{7259EC45-AD9C-4A93-AB1E-0CD273FE4F84}](https://github.com/user-attachments/assets/3e012624-4e9e-461c-9b19-77b08ed93b54)

**Comment by gaboolic** [comment]
以前是把41448大字表单独加载 优先级设置的非常低，然后让41448在后面的
现在8105和41448在同一个翻译器同台竞技了，引起有的41448大字频率超过了8105
我后面看看怎么优化吧

**Comment by gaboolic** [comment]
先在custom_phrase.txt里改下
滚	gy	2

**Comment by gaboolic** [comment]
我这是用知乎语料分词做的词频，我看了一下
很多人把丨 和|混用了，本应该是用|当分割线的 导致丨的词频有点过高
