### ISSUE TITLE
上次反馈安卓下安装同文输入法，繁体无效

### ISSUE THREAD

**Issue by awyc** [gaboolic/rime-shuangpin-fuzhuma#110]
![image](https://github.com/user-attachments/assets/f816b927-71c0-4063-a38f-6664e03269c4)
![image](https://github.com/user-attachments/assets/bffcd7d4-7662-456c-b023-d501d62090e1)
![image](https://github.com/user-attachments/assets/2749083a-56da-4238-8295-103fb51ae986)
![image](https://github.com/user-attachments/assets/da9914c7-c33b-4112-bbd6-0a4cf7fbebf6)
怎么切换都没用

**Comment by gaboolic** [comment]
用的是同文原始皮肤吗 如果是 去同文群问问 或者下载最新的版本试试
