### ISSUE TITLE
请教如何关闭超级简拼？

### ISSUE THREAD

**Issue by bilirod** [gaboolic/rime-shuangpin-fuzhuma#114]
比如打“人”字，单输入一个"r"可以让“人”出现在第一位，但是输入"ren"，第一个位置会是“任”。
<img width="131" alt="Snipaste_2024-11-18_00-14-43" src="https://github.com/user-attachments/assets/e586fab2-7a06-4814-8ea5-debd0d7a1e7d">
<img width="108" alt="Snipaste_2024-11-18_00-14-26" src="https://github.com/user-attachments/assets/30caf5e6-5b09-465f-9657-6d09eeecdd97">

**Comment by gaboolic** [comment]
在custom_phrase里面修改

**Comment by Rurinn** [comment]
“超级简拼：1码、2码、3码时，按下Tab（或者是/，或者是。都可以）自动上屏1字、2字词、3字词”
![Image](https://github.com/user-attachments/assets/ebdc2a41-82be-45f7-8e8c-f652191e7b6a)
关于图中的超级简拼功能，请问应该在哪里如何关闭？
