### ISSUE TITLE
关于辅助码能不能设置成开关？

### ISSUE THREAD

**Issue by sullevy** [gaboolic/rime-shuangpin-fuzhuma#119]
主要在手机上使用，因为用的是12键布局，所以会天然导致重码比较多。

由于模糊音设置的原因，默认设置中会自动匹配3码辅助码，导致长句输入中乱组的现象。

例如
今天吃饭了

1 默认输入的情况，会自动匹配辅助码的第三位
![IMG_20241215_103153.jpg](https://github.com/user-attachments/assets/20d882ca-531e-42d2-aa3d-caec1961e311)

2 强制使用拼音分词符号进行切分
![Screenshot_2024-12-15-08-52-44-320_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/12732d44-2865-4ab1-bc33-5934c77e2890)

3 使用3码进行词组输入 避免乱组词
![IMG_20241215_103211.jpg](https://github.com/user-attachments/assets/9326b312-72cf-4a6e-8011-c77686d8f3b0)

我在配置当中启用了tab辅助码
但没有发现关闭三码自动辅码的地方
所以能不能做一个开关进行切换
这样在手机上使用时，其实可以直接点选

**Comment by sullevy** [comment]
另外，在9宫或者12、14宫布局下，还可以单独添加五笔画来筛选，看到有一个[search.lua](https://github.com/mirtlecn/rime-radical-pinyin/blob/master/search.lua.md)
应该可以支持
基于 stroke 用非26字母作为 横竖撇捺折，参与筛选

**Comment by gaboolic** [comment]
这个项目主打的是效率，主要在电脑上用，或者手机26键上用，致力于提供一个最具有效率的双拼加形输入方案
你的需求 可以用我另一个项目 白霜拼音，https://github.com/gaboolic/rime-frost  是用的search.lua  用`引导辅助码的
