### ISSUE TITLE
【需求】生成/发布 flypy_zrm 版的词库

### ISSUE THREAD

**Issue by bosbyj** [gaboolic/rime-shuangpin-fuzhuma#12]
目前发现有不少类似我这样的用户，参见隔壁repo的讨论
https://github.com/ksqsf/rime-moran/issues/41

是否有可能发布一个这样的杂交版呢？谢谢

**Comment by gaboolic** [comment]
可以 不过不一定是生成新词库，这样文件太大了。用已有的词库xform一下就可以了 我有空了弄一个



---Original---
From: ***@***.***&gt;
Sent at: 2024年4月27日(Sat) AM8:41
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gaboolic/rime-shuangpin-fuzhuma] 生成/发布 flypy_zrm 版的词库 (Issue #12)




 
目前发现有不少类似我这样的用户，参见隔壁repo的讨论
 ksqsf/rime-moran#41
 
是否有可能发布一个这样的杂交版呢？谢谢

**Comment by gaboolic** [comment]
我后面也有计划做一个新的辅助码，在易学的基础上 区分度更高，没有歧义不用加容错码 欢迎关注



---Original---
From: ***@***.***&gt;
Sent at: 2024年4月27日(Sat) AM8:41
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gaboolic/rime-shuangpin-fuzhuma] 生成/发布 flypy_zrm 版的词库 (Issue #12)




 
目前发现有不少类似我这样的用户，参见隔壁repo的讨论
 ksqsf/rime-moran#41
 
是否有可能发布一个这样的杂交版呢？谢谢

**Comment by jack2game** [comment]
试试moflice？
https://github.com/jack2game/rime-moflice

**Comment by gaboolic** [comment]
“自然码弱点在于，容错码多，而组词的时候，只能记忆一种拆字方式。鹤形唯一性好些。”
看来你也两者都用过了，我和你的观点差不多
不过我现在鹤形用久了也感觉到一些问题，我重新搞了一个拆分。还没发布。
基于字形描述信息的递归拆分。这样能解决赢嬴，辩辨，班斑 弼粥 衍衔 微徵 衷袤的问题，末形不同了就
也能做到末形相同时，末码也相同

**Comment by gaboolic** [comment]
我现在搞了拆分和码表都开源的墨奇音形
