### ISSUE TITLE
部分字拆分问题

### ISSUE THREAD

**Issue by Lepton-Lee** [gaboolic/rime-shuangpin-fuzhuma#123]
- 㯕字拆为：木卄二一八斤，字根表里有{其上}，不清楚为什么要拆得这么七零八碎，这么拆谁能打得出来啊。正常应该是：木{其上}八斤（muqibajb）

- 㿇字拆为：疒习习白，但是az模式输入bkxixibd，打不出来。

**Comment by gaboolic** [comment]
㾴还未收录 目前只收录了4万字

㯕字拆为：木卄二一八斤  木{其上}八斤  最终的结果都是木和斤，没有问题

㿇字拆为：疒习习白，但是az模式输入bkxixibd，打不出来。 （az模式是用的别人的方案，收字也比较少 可以用墨奇码拆字模式amq：amqbxxb）

**Comment by gaboolic** [comment]
目前拆字相关的有amq（墨奇码拆字模式）   alf（自然两分拆字）  az（部件组字）

㯕用墨奇码拆字和自然两分都能打，az模式字比较少打不出来

**Comment by gaboolic** [comment]
经过综合考虑、重码等等，{其上}没有必要
