### ISSUE TITLE
【需求】可不可以加入小鹤的符号码表

### ISSUE THREAD

**Issue by verve91** [gaboolic/rime-shuangpin-fuzhuma#13]
就是那个符号码表，小鹤官网的那个
[导出 - 主码 - 符号.txt](https://github.com/gaboolic/rime-shuangpin-fuzhuma/files/15140586/-.-.txt)
也不是说就是按照他这个，就是类似那个大写数字那样的，给一个指定的字母引导
比如我想输入希腊字母，可以给定一个大写的XD就是引导大写的希腊字母，输入引导XX就是输入小写的希腊字母，后面是输入 希腊字母的读音首字母
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/62169380/79bf255b-fae6-46da-9988-8ddda78a4fee)
，这个样子的，比如我想输入α ，输入XXa ，我想输入β，输入XXb。大写的这个样子Δ，输入XDd。
还有一些其他的常用其他字符，比如①这样的。

俺就是随便说说，不用太过介意

**Comment by gaboolic** [comment]
你说的会考虑，有好的配置就可以搬运过来
如果有较强的需求 你可以先加到custom_phrase.txt文件里

**Comment by ChihoiTse** [comment]
目前需要输入①这样的符号的话，就只能在custom_phrase.txt里面加了是吗

**Comment by bosbyj** [comment]
> 目前需要输入①这样的符号的话，就只能在custom_phrase.txt里面加了是吗？`user.dict.yaml`和`custom_phrase.txt`自定义的词，哪个权重更高？

同关注。

我发现txt码表权限高些。
yaml词库，权重我调高了，但一样会被translator降权。

目前在用 custom phrase txt 放简码。

不知道怎样才能利用好 user.dict.yaml

**Comment by gaboolic** [comment]
> 目前需要输入①这样的符号的话，就只能在custom_phrase.txt里面加了是吗？`user.dict.yaml`和`custom_phrase.txt`自定义的词，哪个权重更高？

custom_phrase.txt优先级最高
在哪里加都行。
输入①的话， /szq 就行了，可以看看symbols_caps_v.yaml

**Comment by gaboolic** [comment]
> > 目前需要输入①这样的符号的话，就只能在custom_phrase.txt里面加了是吗？`user.dict.yaml`和`custom_phrase.txt`自定义的词，哪个权重更高？
> 
> 同关注。
> 
> 我发现txt码表权限高些。 yaml词库，权重我调高了，但一样会被translator降权。
> 
> 目前在用 custom phrase txt 放简码。
> 
> 不知道怎样才能利用好 user.dict.yaml

custom phrase txt 就是放简码的。
user.dict.yaml 是放用户自定义的词的，比如矧码 空明码 跟打器 并击这些没收录的词

**Comment by gaboolic** [comment]
oba 一鱼
obq 犭 求 具其上部

**Comment by gaboolic** [comment]
希腊字母
ofxx αβγ
ofxd ΑΒΓ

**Comment by verve91** [comment]
作者大大威武

**Comment by ChihoiTse** [comment]
感谢作者！补充一下，给路过的朋友看。o符快符使用可以参考：[https://flypy.cc/#/fh。](https://flypy.cc/#/fh%E3%80%82)

**Comment by verve91** [comment]
作者这个是精简过的，改得还挺清晰的，

**Comment by bosbyj** [comment]
希腊字母，数学/物理 用的比较多。恭喜！
