### ISSUE TITLE
关于u 和 v

### ISSUE THREAD

**Issue by kiyurei** [gaboolic/rime-shuangpin-fuzhuma#14]
打“去”这个字的时候会习惯性打qv，而不是qu。所以尝试注释了flypy_flypy.schema.yaml的第129行，但是再打qv之后会出现“其中”这个词，在没注释前，qv只会出现“其中”这一个词，所以能否把它关闭掉。类似的打yv会出现”一直“这个词等。

**Comment by gaboolic** [comment]
是的， `# - derive/^([jqxy])u/$1v/`  控制的是qu qv，ju jv的互相飞键
你可以再编辑一下custom_phrase.txt把“其中” “一直” 去掉

**Comment by gaboolic** [comment]
另外 “去” 是1简字，打q 就出来了

**Comment by kiyurei** [comment]
懂了，感谢解答
