### ISSUE TITLE
以词定字

### ISSUE THREAD

**Issue by bosbyj** [gaboolic/rime-shuangpin-fuzhuma#15]
雾凇自带的插件，貌似没有启用

-- 以词定字，可在 default.yaml → key_binder 下配置快捷键，默认为左右中括号 [ ]
select_character = require("select_character")

我在custom.yaml里，打了补丁，没能生效

  'engine/processors/@before 0':
    lua_processor@select_character_processor

**Comment by gaboolic** [comment]
雾凇自带的以词定字 和本仓库的码表的辅助码有些冲突，辅助码是[引导的
因为本仓库有辅助码可以选字，以词定字的实用性不太高

**Comment by bosbyj** [comment]
感谢回复，思路明白了，明天我再研究下配置文件。

**Comment by bosbyj** [comment]
patch:
  engine/processors/@before 0: lua_processor@select_character

然后加上快捷键设定，可以使用了

  key_binder:
    # Lua 配置: 以词定字（上屏当前词句的第一个或最后一个字），和中括号翻页有冲突
    select_first_character: "comma"
    select_last_character: "period"

经测试，发现用【】也没问题
