### ISSUE TITLE
请问一下这个方案适用于同文输入法吗

### ISSUE THREAD

**Issue by zghnby0825** [gaboolic/rime-shuangpin-fuzhuma#16]

**Comment by gaboolic** [comment]
我很久之前用过 当时手机的trime好像自带的文件比电脑上的rime少，一些功能没有
但理论上是适用的，你可以测试一下，如果不行 我可以看看怎么修
我现在手机上用的fcitx5-android版的rime，和电脑上的体验完全一致

**Comment by qiangu2020** [comment]
@gaboolic fcitx5-android版的rime怎么可以装上你的配置呀

尝试直接将文件复制到/Android/data/org.fcitx.fcitx5.android/files/data/rime文件夹，但是不知道怎么让他起作用
