### ISSUE TITLE
几个配置问题

### ISSUE THREAD

**Issue by suibianzai** [gaboolic/rime-shuangpin-fuzhuma#17]
作者你好，首先谢谢你分享的方案，我刚刚开始使用，碰到一些问题，希望得到解答：

1、 default.yaml等文件自动挪位：
复制完配置文件后，我按照“常见问题”里的说明，启动了使用,和.来翻页，重启后，rime用户配置文件夹下面自动新创建了一个“build”问键，defult.yaml等文件就被挪到了build文件夹下，而且我打开default.yaml，里面的内容也边过了，和一开始的不一样了。有些文件在rime和build两个文件夹下面同时存在，比如flypy_flypy.schema.yaml。build文件夹的内容截图如下：
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/6949f33a-87b3-46aa-8d0f-004e68554628)
我尝试清除配置文件夹，重新复制，还是一样的情况，请问是怎么回事？应该怎么处理？同时存在的文件以哪个版本为准？

2、小鹤双拼下标点符号如何自动上屏？像“、”“~”等标点符号，无法自动上屏，还需要再按空格选择一次。请问如何设置自动上屏？
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/1f673623-e014-4ee8-ad3d-c482ed4458f3)

3、用户短语的排序无法生效，我所有的自定义短语都会出现在第一个候选词，不会出现在自定义的顺位上，请问是怎么回事？
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/e3a07f6d-6545-4010-9197-2f0100cd87c4)
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/0fd2be9e-36d9-42bb-9da8-af409fdfc9f3)

**Comment by gaboolic** [comment]
1 build文件夹里的不用管，是rime程序自己生成的。所以外面有一份，build里面也有一份，是正常的
2 ~ 是可以自动上屏的。~【】「」；：‘“、《》，。？ 都可以自动上屏。不能自动上屏的只有两个| （出来多选·|｜§¦）和/ （用来引导/fh）
3 自定义短语的数字不是顺位的意思，越大越优先，数字越大 就越在第一位。例如q是去 3 ，其实 2，去不去 1

**Comment by gaboolic** [comment]
2 标点符号自动上屏的配置是在default.yaml的punctuator:half_shape，如果只有一个候选 并且没用[]数组， 就是自动上屏例如'~' : '~'

你可以参考
```
half_shape:
    ',' : '，'
    '.' : '。'
    '<' : '《'
    '>' : '》'
    '/' : [ /, ÷ ]
    '?' : '？'
    ';' : '；'
    ':' : '：'
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : '、'
    "|": ["·", "|", "｜", "§", "¦"]
    '`' : '、'
    '~' : '~'
    '!' : '！'
    '@' : '@'
    '#' : '#'
    '%' : '%'
    '$' : '¥'
    '^' : '……'
    '&' : '&'
    '*' : '*'
    '(' : '（'
    ')' : '）'
    '-' : '-'
    '_' : ——
    '+' : '+'
    '=' : '='
    '[' : '【'
    ']' : '】'
    '{' : '「'
    '}' : '」'
```

**Comment by suibianzai** [comment]
非常谢谢作者的回复！
1、关于符号自动上屏，我重新配置了一次，现在是自动上屏了，搞不懂为什么~
2、关于自定义短语后面的那个数字 我一直以为是候选词序号 原来搞错了 是我没仔细审题x x
3、前两天你没回复的时候，我自己也去研究了一下rime的配置规则，原来rime打补丁的原理是：程序文件夹下的.yaml文件+rime用户配置文件夹下的同名.custom.yaml（补丁文件）→在build文件夹下生成最终执行的.yaml文件。补丁的好处是，更新、重装程序，不会影响用户的自定义设置，所以很多人建议用户自己的配置在.custom.yaml文件里面设置，补丁的应用优先级应该是最大的。我自己写了一下最主要的两个配置文件的补丁：可以供其他人参考：
[default.custom.yaml（输入法方案选择、候选词个数、翻页）](https://1drv.ms/u/s!At8-wrICdEgUgYwB7qsojlQvSf_aag?e=BMHNld)
[weasel.custom.yaml（外观，自己用的皮肤直接改在这里就行了）](https://1drv.ms/u/s!At8-wrICdEgUgYtg3U4g8aH7BZubpQ?e=oaHR9H)
4、关于候选词个数，我设定是9个，但为什么显示的永远是8个？😂
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/73c9c0ff-196b-439b-8132-f10832174832)
5、关于输入/bq显示表情，我这边只能看到3个表情，我想再加几个表情，请问应该去哪个文件下设置呢？
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/42022663/e6dfacc3-e751-44d0-854b-971ea59f2385)

**Comment by gaboolic** [comment]
4 你全局搜一下 page_size，看看是哪里还有8？
```
menu:
  page_size: 8
```

5 在symbols_caps_v.yaml
```
#象棋、麻将、色子、扑克
  '/xq': [ ♔, ♕, ♖, ♗, ♘, ♙, ♚, ♛, ♜, ♝, ♞, ♟ ]
  '/mj': [ 🀀, 🀁, 🀂, 🀃, 🀄, 🀅, 🀆, 🀇, 🀈, 🀉, 🀊, 🀋, 🀌, 🀍, 🀎, 🀏, 🀐, 🀑, 🀒, 🀓, 🀔, 🀕, 🀖, 🀗, 🀘, 🀙, 🀚, 🀛, 🀜, 🀝, 🀞, 🀟, 🀠, 🀡, 🀢, 🀣, 🀤, 🀥, 🀦, 🀧, 🀨, 🀩, 🀪, 🀫 ]
  '/sz': [ ⚀, ⚁, ⚂, ⚃, ⚄, ⚅ ]
  '/pk': [ ♠, ♥, ♣, ♦, ♤, ♡, ♧, ♢ ]
#表情
  '/bq': [ ☻, ☺, ☹ ]
#天气
  '/tq': [ ☀, ☁, ⛅, ⛈, ⛆, ☂, ☔, ☃, ⛄, ⛇ ]
```

**Comment by suibianzai** [comment]
4、找到了，是拼音方案文件里的候选词数量没改，我用的小鹤双拼，就是flypy_flypy.schema.yaml，不过我比较喜欢在补丁文件里面改，新建一个flypy_flypy.custom.yaml，输入：
```
patch:
  menu/page_size: 9
```
5、设置成功了 谢谢！
