### ISSUE TITLE
【需求】关于小鹤音型 快符o符分号符

### ISSUE THREAD

**Issue by lakuhana** [gaboolic/rime-shuangpin-fuzhuma#19]
能不能像官网一样，弄一份配置完全使用4码，也就是`小鹤音型`而不是`辅助码`，和官方是一样的，鹤大本身就是更加推荐使用`小鹤音型`。
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/5ef1bbf8-5a84-49cb-a3f5-b0944155a6b2)

---

还有`o符`和`快符`，我很喜欢小狼毫的风格，所以我希望在小狼毫能用的上它
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/80905d32-7cbd-4d87-b080-9c097d48fd32)

**Comment by ChihoiTse** [comment]
[amorphobia](https://github.com/amorphobia)[openfly](https://github.com/amorphobia/openfly) 可以参考一下这个，整合一下

**Comment by gaboolic** [comment]
四码上屏的小鹤音形 官方不是提供了吗 https://www.flypy.com/download/    里面也有rime的版本
你追求自动上屏的话，用官方的就好了
自动上屏四码定长只能用小词库，日常并不好用，打单很多，很多词收录的也比较奇怪 :)

**Comment by gaboolic** [comment]
快符 可以考虑加进来

**Comment by ChihoiTse** [comment]
好像是，没有留意到有个鼠须管的。反倒是辅助码没有提供rime版本的。快浮和o符都能加吗？o 符里面快速输入符号，部件和小字这个功能老喜欢了。期待更新

**Comment by ChihoiTse** [comment]
另外不知道怎么设置字的置顶，首字，次首字，等等。比如ui 是 是排第三个的，实际上用的最多，我想把它置顶到第一位去

**Comment by gaboolic** [comment]
是在一简，u上面
需要修改的话 改custom_phrase.txt

**Comment by gaboolic** [comment]
o 符里面快速输入符号，部件和小字    我后面加下

**Comment by ChihoiTse** [comment]
> 是在一简，u上面 需要修改的话 改custom_phrase.txt

**Comment by transread** [comment]
> o 符里面快速输入符号，部件和小字 我后面加下

十份期待这个更新。

有很多自己常用的符号，需要翻好几页才能找到。

PS：请问一下如何在小鹤双拼模式下，使用 symbols_v.yaml 中的符号？

设置过两次，但是都没有成功。

**Comment by ChihoiTse** [comment]
默认的`/`模式下，`/1` `/5~/10`都是正常的。但是在双拼的情况下，`/`出来是
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/ac0bb212-cb92-4b25-992a-c2bef5ac6b26)
这就导致了`/2`没办法得到预期的结果`'v2': [ 二, 贰, ², ₂, Ⅱ, ⅱ, ②, ➁, ❷, ➋, ⓶, ⑵, ⒉, ２, ㊁, ㈡, 弍, 弐, 貮, 㒃, 㒳, 两, 俩, ㆓]`，包括`/3 /4`都是没有反应的。而配置如果使用`v`模式，在双拼下，默认出来的是
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/1293dbae-052a-4292-a738-004b8d9c9003)
所以也就导致v+123都是得不到预期的结果。
建议默认配置改为大写V模式。我这边已经手动修改过了
---
实际上提供的配置里面注释和内容可能是没有匹配上。如下图，注释说的是`v`模式改为`V`，实际上还是`/fh`形式
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/59621b14-e6eb-4211-aa4e-96f0caa4d1a7)

**Comment by gaboolic** [comment]
> > o 符里面快速输入符号，部件和小字 我后面加下
> 
> 十份期待这个更新。
> 
> 有很多自己常用的符号，需要翻好几页才能找到。
> 
> PS：请问一下如何在小鹤双拼模式下，使用 symbols_v.yaml 中的符号？
> 
> 设置过两次，但是都没有成功。

symbols_v.yaml 中的符号 比如可以使用/fh等等

**Comment by ChihoiTse** [comment]
感谢作者的无私奉献！很开心，还有个`；`分号符功能能不能一起实现一下呀~
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/64679359-0a3d-4424-84bf-c33e8ebbc6de)

**Comment by ChihoiTse** [comment]
快符分号符已经拿过来了，自己实在是没有这个能力去实现这个功能，作者大大看看能不能把这部分也实现一下呀~
从官方提供鼠须管里面拿出来的
[flypy_sys.txt](https://github.com/gaboolic/rime-shuangpin-fuzhuma/files/15259875/flypy_sys.txt)

```
# 快符
：“	;q
？	;w
（	;e
）	;r
@	;t
·	;y
+	;u
-	;i
[	;o
]	;p
！	;a
……	;s
、	;d
《	;g
*	;h
/	;j
(	;k
)	;l
“	;z
→	;x
”	;c
——	;v
》	;b
<	;n
>	;m
```

**Comment by gaboolic** [comment]
> 快符分号符已经拿过来了，自己实在是没有这个能力去实现这个功能，作者大大看看能不能把这部分也实现一下呀~ 从官方提供鼠须管里面拿出来的 [flypy_sys.txt](https://github.com/gaboolic/rime-shuangpin-fuzhuma/files/15259875/flypy_sys.txt)
> 
> ```
> # 快符
> ：“	;q
> ？	;w
> （	;e
> ）	;r
> @	;t
> ·	;y
> +	;u
> -	;i
> [	;o
> ]	;p
> ！	;a
> ……	;s
> 、	;d
> 《	;g
> *	;h
> /	;j
> (	;k
> )	;l
> “	;z
> →	;x
> ”	;c
> ——	;v
> 》	;b
> <	;n
> >	;m
> ```

这样 会造成单独输入分号不能直接上屏 要按空格。不太想这样，还是希望所有标点尽量都能直接上屏
如果你希望这样的话，理论上把这段加到置顶短语，再把;加到字母表就行。
字母表是
```
speller:
  # 如果不想让什么标点直接上屏，可以加在 alphabet，或者编辑标点符号为两个及以上的映射
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA[
  # initials 定义仅作为始码的按键，排除 ` 让单个的 ` 可以直接上屏
  initials: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  # 第一位<空格>是拼音之间的分隔符；第二位<'>表示可以手动输入单引号来分割拼音。
```

**Comment by ChihoiTse** [comment]
按照这个方法确实是可以的；我还以为只要修改了`default.yaml`里面的`half_shape，让；号不会自动上屏就行了呢。我就说怎么没生效，原来是要把`speller`里面的内容也一并修改了才可以使用`；+q`的形式。

好像只有`alphabet`和`initials`同时修改才会有效果，单改一个是没有效果的。那这样的话，你的配置里面`alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA[`最后的`[`应该是不起作用的吧

**Comment by ChihoiTse** [comment]
如果能用`取消自动上屏+置顶词`的方式实现`；+key`的功能的话，是不是`/+key`这个功能一样能用同样的方式实现XD；
 采用symbols的方式和`取消自动上屏+置顶词`的方式有什么区别，哪个更优？
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/eea1a6e0-e151-4f8f-b408-07d032e7062b)

**Comment by gaboolic** [comment]
> 按照这个方法确实是可以的；我还以为只要修改了`default.yaml`里面的`half_shape`，让`；`号不会自动上屏就行了呢。我就说怎么没生效，原来是要把`speller`里面的内容也一并修改了才可以使用`；+q`的形式。
> 
> 好像只有`alphabet`和`initials`同时修改才会有效果，单改一个是没有效果的。那这样的话，你的配置里面`alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA[`最后的`[`应该是不起作用的吧

initials 是初始，alphabet是所有的字母表。最后的`[` 意思是[不在初始，可以直接上屏，但是打字时可以加[ 不上屏
例如打 ni[rx 是“你”。然后我把[ 派生了一个不带[版本的，打不打[都行。打[的好处是准确，rime能知道[后面是辅助码，不会组合乱。不打[有时候会组合乱。比如  debu 分不清你是打的“的”（de[bu）还是 “的不”（dabu）

**Comment by gaboolic** [comment]
> 如果能用`取消自动上屏+置顶词`的方式实现`；+key`的功能的话，是不是`/+key`这个功能一样能用同样的方式实现XD； 采用symbols的方式和`取消自动上屏+置顶词`的方式有什么区别，哪个更优？ ![image](https://private-user-images.githubusercontent.com/49972747/329318765-eea1a6e0-e151-4f8f-b408-07d032e7062b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjI4NTcsIm5iZiI6MTcxNTMyMjU1NywicGF0aCI6Ii80OTk3Mjc0Ny8zMjkzMTg3NjUtZWVhMWE2ZTAtZTE1MS00ZjhmLWI0MDgtMDdkMDMyZTcwNjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYjY0OTdmMGQ3NGViZjBmNDhmNmQzNjM2OWM4MGU3NGYyNmZhN2M1NjgyNDdmYTdiNTJkNGMyMmFlYmE2ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lVENkHoKKsgArp9ZXI1ZhT96k2JbyQc07IRtTEzzHVs)
> 
> 随便试了一下，确实是可以 ![image](https://private-user-images.githubusercontent.com/49972747/329319491-d02a86d7-9bd0-4056-ac4a-3ada4d82bade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjI4NTcsIm5iZiI6MTcxNTMyMjU1NywicGF0aCI6Ii80OTk3Mjc0Ny8zMjkzMTk0OTEtZDAyYTg2ZDctOWJkMC00MDU2LWFjNGEtM2FkYTRkODJiYWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YTVhNjkyNDg4NDFiNjYyMjI3NzJiMDE0ZGM3YzI1NDI4NjQyOTdjMTU5MmEwMTM4YjdjYTdhNzU4ZjYyODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YStgumIkgJ2IvE3HcO5BMS7SplPQg5HO-Q9O62K8X7Q)
> 
> 那反过来，`；+key`一样是可以采用symbols的方式实现的吧

我觉得没啥区别

**Comment by gaboolic** [comment]
> > 按照这个方法确实是可以的；我还以为只要修改了`default.yaml`里面的`half_shape`，让`；`号不会自动上屏就行了呢。我就说怎么没生效，原来是要把`speller`里面的内容也一并修改了才可以使用`；+q`的形式。
> > 好像只有`alphabet`和`initials`同时修改才会有效果，单改一个是没有效果的。那这样的话，你的配置里面`alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA[`最后的`[`应该是不起作用的吧
> 
> initials 是初始，alphabet是所有的字母表。最后的`[` 意思是[不在初始，可以直接上屏，但是打字时可以加[ 不上屏 例如打 ni[rx 是“你”。然后我把[ 派生了一个不带[版本的，打不打[都行。打[的好处是准确，rime能知道[后面是辅助码，不会组合乱。不打[有时候会组合乱。比如 debu 分不清你是打的“的”（de[bu）还是 “的不”（dabu）

我是把常用的字例如“的” 的辅助码去掉了。之前 打“debuui” 出现的是“的是” 而不是“的不是”，很尴尬……
我还用lua 来4码的时候把词提前，规避 zssr  总算和纵的问题，类似的还有jiee  饥饿和觊等等

**Comment by ChihoiTse** [comment]
挺好的，全码改3码。最后的`[`我试过确实好像没什么效果，就算在alphabet加了initials不加，打字期间按`【`，一样会自动上屏，除非切换英文输入`[`，再切换回来，如果是这么操作的话，还不如直接使用`'`分号来的直接
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/e998a3b3-bb98-4c9d-acf7-1b4a700286ed)
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/1e2c9802-7c81-4046-8d95-518ce6092f62)

**Comment by gaboolic** [comment]
你nirx    ni[rx 都行。[就是p右边直接按 不按shift啥的

**Comment by gaboolic** [comment]
> 挺好的，全码改3简来规避这个问题。
> 
> > 但是打字时可以加[ 不上屏 例如打 ni[rx 是“你”。然后我把[ 派生了一个不带[版本的，打不打[都行。打[的好处是准确，rime能知道[后面是辅助码，不会组合乱。
> 
> 最后的`[`我试过确实好像没什么效果，就算在alphabet加了initials不加，打字期间按`【`，一样会自动上屏，除非切换英文输入`[`，再切换回来，如果是这么操作的话，还不如直接使用`'`分号来的直接。 ![image](https://private-user-images.githubusercontent.com/49972747/329492866-e998a3b3-bb98-4c9d-acf7-1b4a700286ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjg3MTIsIm5iZiI6MTcxNTMyODQxMiwicGF0aCI6Ii80OTk3Mjc0Ny8zMjk0OTI4NjYtZTk5OGEzYjMtYmI5OC00YzlkLWFjZjctMWI0YTcwMDI4NmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMGMxYTk1NjAxYmE3OGRjMzc0N2M0MWEzYTRiYzVjYjQyZWY3ZDg3ZDk2YjQwNzU0ODA1MjQ0MzJhMzAxZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4eviI1WlgjYFIAwMFytX6q3Ets-MYcxqMkcvrcoGz9s) ![image](https://private-user-images.githubusercontent.com/49972747/329492942-1e2c9802-7c81-4046-8d95-518ce6092f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjg3MTIsIm5iZiI6MTcxNTMyODQxMiwicGF0aCI6Ii80OTk3Mjc0Ny8zMjk0OTI5NDItMWUyYzk4MDItN2M4MS00MDQ2LThkOTUtNTE4Y2U2MDkyZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxODhmMmJkOGJmNGMzZWI4NjAyMTY5NzY4NGYwMTg5OWZiYzM2Y2JiZDI5NTZiNTM0OGQ3Mjg4MTE2ZGQwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AP_U6whF-UhbeO3swHUehmYOKrA9oTLBVX6h3DImawg)
> 
> 不知道是哪里问题呢？没办法像你那样打`ni[rx`

因为我已经把“的”的全码去掉了 打debu 出不来“的”了

**Comment by gaboolic** [comment]
xdm 我建了个q群 一起来玩啊 696353204
