### ISSUE TITLE
有时候不想用辅助码，可以让他临时不出现吗比如这种情况出错

### ISSUE THREAD

**Issue by verve91** [gaboolic/rime-shuangpin-fuzhuma#2]
如图
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/62169380/6e574a43-29d1-4faf-b5ed-1fb41d8e4c69)

我想要的是“怎们说的不一样”，输入短词很舒服，这样的回去改肯定没问题，但是要可以不改是不是更舒服

**Comment by gaboolic** [comment]
有点尴尬，在小鹤里面，“的”拆分正好是白勺（b u)   debu的结合优先级更高
我能想到的一个不完美的方式是把“的”的全码去掉，反正直接打“d”就是“的”

**Comment by verve91** [comment]
我打开调频了，是不是脱离你做这个配置的初衷了😂

**Comment by verve91** [comment]
我还把你费劲改掉的中英混输加上了🤣，简直叛逆

**Comment by gaboolic** [comment]
> 我打开调频了，是不是脱离你做这个配置的初衷了😂

开调频 日常用没问题

**Comment by gaboolic** [comment]
你更新下 我把“的”全码去了

**Comment by verve91** [comment]
好嘞，麻烦了😂
