### ISSUE TITLE
【bug】R键引导输入大写数字无效 小键盘上的数字自动上屏

### ISSUE THREAD

**Issue by tianyiytw** [gaboolic/rime-shuangpin-fuzhuma#20]
按R键后出现3个候选字词，再按数字键就选字词上屏了，无法实现输入大写数字功能。尝试过大小写R，切换中英文，重新安装替换最新配置文件均无效。U键N键也没有相应效果，e键ab键az键这些可以正常引导相应功能。
请问是需要额外按什么键，还是修改什么设置。

**Comment by gaboolic** [comment]
要按大写的R  就是shift+R才行。没有特殊配置了。我在mac和Linux测试均生效
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/3831173/0feef147-cbf5-40ba-a1ad-98fc919a30b0)

**Comment by tianyiytw** [comment]
谢谢，按shift+R/U/N确实可以了。不过发现只能用主键盘区的数字键输入数字，不能用小键盘区的。

**Comment by gaboolic** [comment]
这个应该没有限制才对，小键盘单独输入能输入数字吗



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月5日(Sun) AM9:13
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gaboolic/rime-shuangpin-fuzhuma] R键引导输入大写数字无效 (Issue #20)




 
谢谢，按shift+R/U/N确实可以了。不过发现只能用主键盘区的数字键输入数字，不能用小键盘区的。

**Comment by tianyiytw** [comment]
小键盘能正常输入数字。按shift+R出现（数值超限）两个候选，再按小键盘区1和2会上屏（数值超限），其他数字键无反应。
![Quicker_20240505_094858](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/61279201/13784e8a-adb1-46cc-bcaf-93aed7580a8d)
还有手机上能实现大写数字的功能吗？手机上不能同时按shift+R，试了下，没试出来。

**Comment by gaboolic** [comment]
我虽然没小键盘 但我用改键软件改了一个小键盘的1  确实复现了
我盲猜一下 是Lua的问题，我尝试解决下

**Comment by gaboolic** [comment]
你是在哪个平台上，我试了下mac的squirrel 小键盘不行，mac的fcitx5 for macos是可以的
现在感觉不是配置的问题了

**Comment by tianyiytw** [comment]
> 你是在哪个平台上，我试了下mac的squirrel 小键盘不行，mac的fcitx5 for macos是可以的 现在感觉不是配置的问题了

win11

**Comment by bosbyj** [comment]
> 小键盘能正常输入数字。按shift+R出现（数值超限）两个候选，再按小键盘区1和2会上屏（数值超限），其他数字键无反应。 ![Quicker_20240505_094858](https://private-user-images.githubusercontent.com/61279201/327984025-13784e8a-adb1-46cc-bcaf-93aed7580a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDQ1MjksIm5iZiI6MTcxNTA0NDIyOSwicGF0aCI6Ii82MTI3OTIwMS8zMjc5ODQwMjUtMTM3ODRlOGEtYWRiMS00NmNjLWJjYWYtOTNhZWQ3NTgwYThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAxMTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1N2IxNmMxYWFkNDFjMzE4ZjJkMzkyMDhjZWYyZWM1MGU5MGNhNDk2NTRiZTEzOWI2ZmQ4YTA0Zjg5ZDc4MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZ1Y1BLi2BdUsiO_bVrKwqhIE4rVX-FnNRCgNJwdP9k)

官方0.15.0 小狼毫 可以复现。
有可能是 librime lua版本问题。

**Comment by gaboolic** [comment]
> > 小键盘能正常输入数字。按shift+R出现（数值超限）两个候选，再按小键盘区1和2会上屏（数值超限），其他数字键无反应。 ![Quicker_20240505_094858](https://private-user-images.githubusercontent.com/61279201/327984025-13784e8a-adb1-46cc-bcaf-93aed7580a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDQ1MjksIm5iZiI6MTcxNTA0NDIyOSwicGF0aCI6Ii82MTI3OTIwMS8zMjc5ODQwMjUtMTM3ODRlOGEtYWRiMS00NmNjLWJjYWYtOTNhZWQ3NTgwYThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAxMTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1N2IxNmMxYWFkNDFjMzE4ZjJkMzkyMDhjZWYyZWM1MGU5MGNhNDk2NTRiZTEzOWI2ZmQ4YTA0Zjg5ZDc4MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZ1Y1BLi2BdUsiO_bVrKwqhIE4rVX-FnNRCgNJwdP9k)
> 
> 官方0.15.0 小狼毫 可以复现。 有可能是 librime lua版本问题。

我也觉得是 librime lua版本问题，因为fcitx5 for macos是好的。

二位 我看到雾凇的仓库里有一个专门解决这个问题的配置，稍后我更新进去
雾凇把小键盘的数字转成123456789了
```
# 将小键盘 0~9 . 映射到主键盘，数字金额大写的 Lua 如 R1234.5678 可使用小键盘输入
    - {accept: KP_0, send: 0, when: composing}
    - {accept: KP_1, send: 1, when: composing}
    - {accept: KP_2, send: 2, when: composing}
    - {accept: KP_3, send: 3, when: composing}
    - {accept: KP_4, send: 4, when: composing}
    - {accept: KP_5, send: 5, when: composing}
    - {accept: KP_6, send: 6, when: composing}
    - {accept: KP_7, send: 7, when: composing}
    - {accept: KP_8, send: 8, when: composing}
    - {accept: KP_9, send: 9, when: composing}
    - {accept: KP_Decimal, send: period, when: composing}
 ```

**Comment by gaboolic** [comment]
更新了，可以再尝试一下
