### ISSUE TITLE
请问可以实现常用字词自动置顶/靠前显示吗

### ISSUE THREAD

**Issue by qiangu2020** [gaboolic/rime-shuangpin-fuzhuma#21]

**Comment by bosbyj** [comment]
置顶，可使用 custom_phrase.txt

自动置顶，需要打开用户词典功能

**Comment by qiangu2020** [comment]
> 置顶，可使用 custom_phrase.txt
> 
> 自动置顶，需要打开用户词典功能

嗯啊，感谢，修改flypy_flypy.schema.yaml enable_user_dict: true 就可以自动置顶

**Comment by qiangu2020** [comment]
字词，用e引导简码，简码取声母

这个取出来的选项有点少，能取常用的吗，比如取自动置顶的/手动置顶的

**Comment by gaboolic** [comment]
e引导简码，简码取声母，这个是只放了3字的词和4字的词
2字的词的简码，有的放在了custom_phrase.txt
确实可以用e引导，但是感觉效率也没提高多少
比如快乐，kkle 4个键，改成e引导 ekl 也就3个键，效率不如3字 4字 多字的提高的多

**Comment by qiangu2020** [comment]
> e引导简码，简码取声母，这个是只放了3字的词和4字的词 2字的词的简码，有的放在了custom_phrase.txt 确实可以用e引导，但是感觉效率也没提高多少 比如快乐，kkle 4个键，改成e引导 ekl 也就3个键，效率不如3字 4字 多字的提高的多

对，的确的，不过，我是发现自动置顶的，在e里面引用没有。这个是可以怎么调整吗

**Comment by gaboolic** [comment]
你是想要e里面 有更多的4字词吗
e里面的4字词在chengyu.dict.yaml，多字词在changcijian.dict.yaml
我想的是把所有4字成语放chengyu.dict.yaml
但还没找到一个好的成语词库

**Comment by qiangu2020** [comment]
> 你是想要e里面 有更多的4字词吗 e里面的4字词、多字词在changcijian.dict.yaml，是固定的 我想的是把所有4字成语放进去 但还没找到一个好的成语词库

对是滴，主要是希望e里面能有自动置顶的字词。目前自动置顶的词好像都在e里面没有

**Comment by gaboolic** [comment]
e里面的词是在dict文件里写死的，做不到动态使用你自己的用户词库……

**Comment by bosbyj** [comment]
我记得txt词库，如custom phrase，是支持动态打字添加，ctrl delete 删除单词的。

但是造词，貌似txt词库写不进去yaml那种 encoder 吧？

也许yaml也能动态增删词语。待研究。

**Comment by qiangu2020** [comment]
> > 置顶，可使用 custom_phrase.txt
> > 自动置顶，需要打开用户词典功能
> 
> 嗯啊，感谢，修改flypy_flypy.schema.yaml enable_user_dict: true 就可以自动置顶

这里自动置顶是根据使用的频次吗，体验下来，是根据最近使用的那个就排在前面

**Comment by gaboolic** [comment]
> > > 置顶，可使用 custom_phrase.txt
> > > 自动置顶，需要打开用户词典功能
> > 
> > 
> > 嗯啊，感谢，修改flypy_flypy.schema.yaml enable_user_dict: true 就可以自动置顶
> 
> 这里自动置顶是根据使用的频次吗，体验下来，是根据最近使用的那个就排在前面

是的
