### ISSUE TITLE
关于飞键 理论指导

### ISSUE THREAD

**Issue by bosbyj** [gaboolic/rime-shuangpin-fuzhuma#22]
开始研究飞键。

咱们schema里的配置，看上去挺科学的，请问是裁缝哥自用总结的吗？还是参照了前人的指导

网上搜了一圈，貌似是从 大牛双拼 开始的
然后在键道得到进一步发展

咱们小鹤/自然系，不知道有没专门的论述

## 飞键 可选择性开启
    # - derive/^([yh])j/$1q/
    # - derive/^qx/qw/
    # - derive/^jn/jv/
    # - derive/^mn/mv/
    # - derive/^jm/jz/
    # - derive/^([y])h/$1g/
    # - derive/^([rgv])f/$1m/
    # - derive/^([rgv])c/$1n/

**Comment by bosbyj** [comment]
https://zhuanlan.zhihu.com/p/611200374?utm_id=0

这篇不错，热力图可供研究。

**Comment by gaboolic** [comment]
是我随便搞了一下，算个demo吧 每个人可以改成自己顺手并且无冲突的就行了
比如r g v拼不成riao giao zhiao 就可以把ao飞到iao上

**Comment by gaboolic** [comment]
但我现在觉得吧，不飞也罢。不飞的话，冲突的键位就能多放几个简码。
比如rm 可以放人们。gm可以放干嘛 感冒啥的。

**Comment by gaboolic** [comment]
老哥 来群里玩696353204

**Comment by bosbyj** [comment]
> 老哥 来群里玩696353204

没有tencent账号，可惜了。
