### ISSUE TITLE
【需求】能加入混合输入日语的开关吗？

### ISSUE THREAD

**Issue by kevian-natucmcpb** [gaboolic/rime-shuangpin-fuzhuma#23]
类似魔然的,取消schema里带"japanese"的两行注释，就能混合输入日语了

**Comment by gaboolic** [comment]
不懂日语，回头研究下，要是好搞就缝进来

**Comment by gaboolic** [comment]
看了一下是有一个日语词库。
可以像英语一样，搞个前缀引导

**Comment by kevian-natucmcpb** [comment]
> 看了一下是有一个日语词库。
> 
> 可以像英语一样，搞个前缀引导

我在魔然的作者和雪星的作者帮助下，勉强把雪星改出来了，但是没有辅助码，混输和日语的辅助码您这边有思路吗？

**Comment by gaboolic** [comment]
> > 看了一下是有一个日语词库。
> > 可以像英语一样，搞个前缀引导
> 
> 我在魔然的作者和雪星的作者帮助下，勉强把雪星改出来了，但是没有辅助码，也没有前缀区分是直接混输的.用前缀的方法应该就能用辅助码了？

不行，我说的是不混输

**Comment by kevian-natucmcpb** [comment]
> > > 看了一下是有一个日语词库。
> 
> > > 可以像英语一样，搞个前缀引导
> 
> > 
> 
> > 我在魔然的作者和雪星的作者帮助下，勉强把雪星改出来了，但是没有辅助码，也没有前缀区分是直接混输的.用前缀的方法应该就能用辅助码了？
> 
> 
> 
> 不行，我说的是不混输

🤔像英语一样加e前缀之类的，然后进行单独输入，重码和选字应该比我目前的混输好很多.您要是没空，如果能列出几个挂接英语用的函数，我应该也能对比处理出来。

**Comment by gaboolic** [comment]
就和挂载笔画输入、仓颉输入、拆字输入差不多
reverse_cj:
  tag: reverse_cj
  dictionary: cangjie5
  enable_completion: true
  prefix: "acj"
  suffix: "'"
  tips: 〔仓颉〕
  preedit_format:
    - xform/^acj/仓颉5:/
    - xlit|abcdefghijklmnopqrstuvwxyz|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|

reverse_stroke:
  tag: reverse_stroke
  dictionary: stroke # stroke
  enable_completion: true
  prefix: "ab"
  suffix: "'"
  tips: 〔筆畫hspnz〕 # 〔筆畫〕
  preedit_format:
    - xlit/hspnz/一丨丿丶乙/

**Comment by gaboolic** [comment]
我把https://github.com/Selaube/rime-jp_sela  缝进去了
词库 合了一下 应该好使了

**Comment by gaboolic** [comment]
https://github.com/gkovacs/rime-japanese
好像这个更全

**Comment by gaboolic** [comment]
不过感觉这些词库都好老。相沢みなみ 都没有

**Comment by kevian-natucmcpb** [comment]
> japanese
> 好像这个更全

我在用的就是这个词库.由于日语的性质，在流行词语上，是很难够得上联网的输入法的，精确按词输入又不需要，rime提供了触摸屏幕和妙控键盘视觉上不分裂的体验更重要.

**Comment by kevian-natucmcpb** [comment]
十分感谢，非常好，输入aj就能切换日语，可以无缝切换，等以后我熟练Rime了，配好词库，给jp_sela加个反查，日语初学者也可以在平板使用了。

**Comment by gaboolic** [comment]
来群里玩 696353204

**Comment by suibianzai** [comment]
> 我把https://github.com/Selaube/rime-jp_sela 缝进去了 词库 合了一下 应该好使了

这个词库是比较老了，我找到一个更大一点的https://github.com/gkovacs/rime-japanese
它里面有好几个词库，能否在aj模式下挂载多个日语词库啊？

**Comment by susanooxyz** [comment]
@gaboolic  我用的是[rime-jaroomaji](https://github.com/lazyfoxchan/rime-jaroomaji)这个词库，但是在aj模式下只能提示一个字，不能连着打。能帮忙看看是怎么回事吗
