### ISSUE TITLE
【BUG】`/`引导时`/2~/5`无法使用

### ISSUE THREAD

**Issue by lakuhana** [gaboolic/rime-shuangpin-fuzhuma#24]
有两个问题：
# `/`模式冲突无法正常使用
默认的`/`模式下，`/1` `/5~/10`都是正常的。但是在双拼的情况下，`/`出来是
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/ac0bb212-cb92-4b25-992a-c2bef5ac6b26)
这就导致了`/2`没办法得到预期的结果`'v2': [ 二, 贰, ², ₂, Ⅱ, ⅱ, ②, ➁, ❷, ➋, ⓶, ⑵, ⒉, ２, ㊁, ㈡, 弍, 弐, 貮, 㒃, 㒳, 两, 俩, ㆓]`，包括`/3 /4`都是没有反应的。而配置如果使用`v`模式，在双拼下，默认出来的是
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/1293dbae-052a-4292-a738-004b8d9c9003)
所以也就导致v+123都是得不到预期的结果。
**而`/`引导在RIME提供的全拼`luna_quanpin`中是正常使用`/3~/5的`**

可以修复一下`/`引导的问题或者**默认配置改为大写V模式**吗？

# `v`模式双拼下冲突+无法出现预期结果

现在提供的两个配置文件`symbols_caps_v.yaml`和`symbols_v.yaml`，分别对应下面两张图

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/ebd97d35-43c1-4368-976f-0a162757a2f0)

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/08920494-01c7-482c-9eb2-a37436835f28)

在`flypy_flypy.schema.yaml`中272行，`__include: symbols_caps_v:/symbols`，默认使用的是`symbols_caps_v.yaml`中的配置，即`/`模式。**模式正常使用**。如图

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/6bdf991e-5d3a-4a73-a580-16a7cd85688c)

而此时我把`flypy_flypy.schema.yaml`中272行修改为`__include: symbols_v:/symbols`，也就是提供配置的`v`模式，模式无法正常使用，如下图

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/662cd085-2bca-4e89-9c2e-12293c41476c)

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/0fb32e3c-fb02-41b9-b745-58fa07f0ecfa)

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/99ae67c8-c1ed-44ba-8c5d-de29fec8845c)

`v`后面无法添加任何数字，又或是`vfh`无法得到预期结果

## 此时我改回默认配置

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/58b12c50-8534-490b-a7e8-1070b5076308)

确保配置正常使用的情况下

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/6bdf991e-5d3a-4a73-a580-16a7cd85688c)

把`symbols_caps_v.yaml`中所有的`/`开头修改为`V`开头，结果是`Vfh`也无法得到预期结果。

---

### 另外

实际上提供的配置里面注释和内容可能是没有匹配上。如下图`symbols_caps_v.yaml中`，注释说的是`v`模式改为`V`，实际上还是`/fh`形式。而`symbols_v.yaml`中也仅仅是小写v模式
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/59621b14-e6eb-4211-aa4e-96f0caa4d1a7)

**Comment by gaboolic** [comment]
我修复一下/ 模式
可能是÷除号引起的 一会试试去掉它管不管用

**Comment by ChihoiTse** [comment]
我试过在`default.yaml`中修改`'/' : [ /, ÷ ]`为`'/' : [ /]`，结果还是`/2~/4`无法使用

**Comment by ChaosAlphard** [comment]
是这种吗
![PixPin_2024-05-09_05-12-37](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/ee8306d6-8725-4413-ba60-e14c548058f9)![PixPin_2024-05-09_05-13-05](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/28647d76-03f2-4e67-9daf-c4e9e6d68a81)![PixPin_2024-05-09_05-12-49](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/7df0f568-aec3-4206-975a-cab48a14034a)

把`recognizer/patterns/punct` 改成 `^/[0-9A-z]+$` 就行
![PixPin_2024-05-09_05-17-02](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/1cd5e510-a9a6-4b61-8c17-8b259a7c6f49)

**Comment by ChaosAlphard** [comment]
话说为啥/0 到 /9 的emoji 都不在候选框显示，/10到是没问题，我这里也不缺字库啊，我用win10自带的表情板都有这个emoji
![图片](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/aaa2ddae-a4e9-4ff4-b541-0f5c739dbad6)

**Comment by ChihoiTse** [comment]
> 是这种吗 ![PixPin_2024-05-09_05-12-37](https://private-user-images.githubusercontent.com/26186575/329051083-ee8306d6-8725-4413-ba60-e14c548058f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzUyODgsIm5iZiI6MTcxNTIzNDk4OCwicGF0aCI6Ii8yNjE4NjU3NS8zMjkwNTEwODMtZWU4MzA2ZDYtODcyNS00NDEzLWJhNjAtZTE0YzU0ODA1OGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA2MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzY2E0YTlmYWQ4MmRjNzQ3M2RhNDJhN2FmODAxZTk5NmFiZmFlMmViYmQ5YjZkOTNjZWE5YjE2NGYyMGQ5MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1MOt74CbpgqCVc8YpJdBh2yAxauMy04-CksQVzrSyGM)![PixPin_2024-05-09_05-13-05](https://private-user-images.githubusercontent.com/26186575/329051112-28647d76-03f2-4e67-9daf-c4e9e6d68a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzUyODgsIm5iZiI6MTcxNTIzNDk4OCwicGF0aCI6Ii8yNjE4NjU3NS8zMjkwNTExMTItMjg2NDdkNzYtMDNmMi00ZTY3LTlkYWYtYzRlOWU2ZDY4YTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA2MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZmQ4M2I1YTg4NGRiMjgyMmVjOGMzYzQ2OThmMjgwNjk5M2FjNjdlM2I0ZWEzYjVkYzJmNzU3NmJhZDY1MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rcr91KOpl-ukaw5onM09aQep-UKZC16l1yhJiUruCxM)![PixPin_2024-05-09_05-12-49](https://private-user-images.githubusercontent.com/26186575/329051104-7df0f568-aec3-4206-975a-cab48a14034a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzUyODgsIm5iZiI6MTcxNTIzNDk4OCwicGF0aCI6Ii8yNjE4NjU3NS8zMjkwNTExMDQtN2RmMGY1NjgtYWVjMy00MjA2LTk3NWEtY2FiNDhhMTQwMzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA2MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDliZTdlMDYyODZmYmI3NDdkOThmMzhkNDM5YjM0NDg3MGJmMTVlYTk2YWJhY2E2NzQ2NDZjNzVmMDMwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D-bVmjE3FKshFUWFiVRW68ibK3EBxG-aKNtdPmbbA3s)
> 
> 把`recognizer/patterns/punct` 改成 `^/[0-9A-z]+$` 就行 ![PixPin_2024-05-09_05-17-02](https://private-user-images.githubusercontent.com/26186575/329052870-1cd5e510-a9a6-4b61-8c17-8b259a7c6f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzUyODgsIm5iZiI6MTcxNTIzNDk4OCwicGF0aCI6Ii8yNjE4NjU3NS8zMjkwNTI4NzAtMWNkNWU1MTAtYTlhNi00YjYxLThjMTctOGIyNTlhN2M2ZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA2MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNmI2NjQxNmQwNzA0Yjg1YTlhMzUxOTFjYjFjOTU4MDJhYjkxMTg3Y2E3ZjkzZGMzNzI4ODc5ZDNjYTA4MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P1szJtHLmXn6pfaAv598CEV3xQUeeZinGvM2N7MSR-s)

这个确实是可以的，感谢，才发现配置里面有注释，要使用`/er`来代替`/2`，这样的话就不需要把`/`的`÷`选项去除了。不过这样的话，选项便无法通过`1~9`快速选择了，是否能像搜狗一样，使用`a~i`进行选择呢？如下图

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/8a90d77a-af9b-44ae-bff3-37c148697191)

当我选择8时，便会

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/a91be0f6-1076-41e0-b9ab-e49a5951f8ab)

**Comment by ChaosAlphard** [comment]
其实原来的配置 `^/[015-9A-Za-z]+$` 也有这个问题，我忽然明白为啥特意把2-4摘出来了，原来是拿来快速选择用的😂，我试一下改一下正则让他排除最后的数字看行不行

**Comment by ChihoiTse** [comment]
好像是，后面这个正则更好用了，感谢。`/ + 1~9数字`无法选10这个，可以用上下+空格选择，将就着用吧。坐等作者修复

**Comment by gaboolic** [comment]
老哥们，这个问题我还没来得及看，如果好使的话，方便提个pr不？我合并一下

**Comment by gaboolic** [comment]
我先改成punct: '^/[0-9A-Za-z]+$' 了

**Comment by gaboolic** [comment]
symbols_caps_v.yaml应该是用/引导的 这个注释我修改了

**Comment by ChihoiTse** [comment]
我对git其实不是特别熟悉哈哈，所以没有提交pr（之后研究一下），我看你已经更新了，似乎是不需要pr了；而且方案还是有一些缺陷：`punct: '^/[0-9A-Za-z]+$' `的时候是无法通过`1~0`进行快速选择的。目前我用的是ChaosAlphard老哥提供的`^/[0-9A-z][0A-z]?[A-z]?+$`，这个方案0的位置可以通过上下+空格进行选择，或者不开启10个选项，只开9个选项也是可以规避掉这个问题；但是最好的方法我认为还是像搜狗一样，当使用`/`引导的时候，可以通过`a~i`进行选择。
先将就用着，看看作者有没有办法解决吧XD

**Comment by gaboolic** [comment]
很强，可以用数字选了

**Comment by ChaosAlphard** [comment]
> 老哥们，这个问题我还没来得及看，如果好使的话，方便提个pr不？我合并一下

提pr了，话说github好像没回复提醒啊_(:з」∠)_，我都没注意到回复

**Comment by ChihoiTse** [comment]
有，watch里面可以选择

**Comment by ChihoiTse** [comment]
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/7d871a49-b39c-4af2-86b2-2b8a892b1a64)
 你这个是怎么弄的

**Comment by ChihoiTse** [comment]
#31

**Comment by ChaosAlphard** [comment]
> ![image](https://private-user-images.githubusercontent.com/49972747/329520967-7d871a49-b39c-4af2-86b2-2b8a892b1a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzE1NzAsIm5iZiI6MTcxNTMzMTI3MCwicGF0aCI6Ii80OTk3Mjc0Ny8zMjk1MjA5NjctN2Q4NzFhNDktYjM5Yy00YWYyLTg2YjItMmI4YTg5MmIxYTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4NTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOTdlZGU5OGJiOTE0YzlmMmJhNzZjZWRkNTIxYzQ1Y2U3MmNhMmJhOGM4Y2NkZDA0MjVjNjc5YzFmMGZiNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1-zuvHptnXanMj92oC8UqQy6l3zGce4kNLQLM3fYqI8) 你这个是怎么弄的

提pr的时候把issues编号带上，比如这个问题是24号就写 `#24`

**Comment by ChihoiTse** [comment]
已提交pr， README可读性优化;fly_fly.schema.yaml配置优化及更正 #31，目前还有小bug待修复：目前正则在`/+number`时无法通过`0`快速选择。

**Comment by ChaosAlphard** [comment]
> 有，watch里面可以选择

watch里面选issues和pull request是嘛，我先选上看看对不对

**Comment by gaboolic** [comment]
老哥们太强了 完美解决
