### ISSUE TITLE
【需求】有几个问题想问一下

### ISSUE THREAD

**Issue by GrandmaChen** [gaboolic/rime-shuangpin-fuzhuma#25]
完全就是我梦想的小鹤音形升级版，大佬牛逼！

有几个问题想问一下

1.  如何设置输入三个字母时出现词组？比如输入uvj时出现”睡觉“（现在只有”帨“），输入”iux“时出现”出现“（现在只有”怵“）。
2.  打二字词时输入辅助码，最后的第五个码是作为前两个字母的辅助码还是后两个字母的辅助码可以设置吗？比如我看首页给的示例，jisub可以打出寄宿，jimsu可以打出极速。但是如果我想用jisum去打出极速（就像jisub打出寄宿那样）就打不出来。

**Comment by gaboolic** [comment]
1 可以把高频的3码的词组手动加到custom_phrase.txt或者user.dict.yaml中。如果想全部的词语都能这样的话，需要改schema.yaml中speller algebra:
```
    - derive/^(..)[[].+$/$1/
    - derive/^(..[[].).+$/$1/
    # - derive/^([jqxy])u/$1v/
    - derive/[[]//
```
这块，给它derive一下，derive成第一个字的前2码和第二个字的第1码。但是不推荐，这样想3码打常用单字就不太方便了

2 不能设置，这个辅助码编码是rime自动计算的，是在字上面的。你说的“想用jisum去打出极速”，有个“小鹭音形”是这样的

**Comment by gaboolic** [comment]
tab方向在 default.yaml
```
key_binder:
  bindings:
    # Tab / Shift+Tab 切换光标至下/上一个拼音
    - { when: composing, accept: Shift+Tab, send: Shift+Left }
    - { when: composing, accept: Tab, send: Shift+Right }
```

**Comment by GrandmaChen** [comment]
不好意思我还是没有懂应该怎么设置三个字母出现词语，我刚开始用rime

**Comment by gaboolic** [comment]
这个解释起来比较复杂，得理解derive https://github.com/rime/home/wiki/RimeWithSchemata
简单说derive就是派生 不改变原始编码，它会新增一种编码
于是利用derive，假如睡觉的原始编码是uv jn， 给它用正则派生出一个uv j

**Comment by bosbyj** [comment]
我唯一的习惯就是打

明天 = mkt_

是在其他平台+整句输入 养成的。我加到 custom_phrase.txt 里了

**Comment by gaboolic** [comment]
目前的置顶短语里，mt是明天 :)  你可以试试

**Comment by gaboolic** [comment]
群 696353204
