### ISSUE TITLE
【需求】能不能加个类似于搜狗的v模式，算式和日期模式

### ISSUE THREAD

**Issue by lakuhana** [gaboolic/rime-shuangpin-fuzhuma#26]
作者大大辛苦了，我觉得搜狗的这个模式挺好用的，不知道能不能加进来，如下：

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/f4136964-4199-4195-b4d8-e34ca3485a7f)

v模式下的日期模式：

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/bf185de2-9c43-4c8b-83f4-7bba8b57241c)

v模式下的算数模式：

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/8f657869-b1c2-4931-9a1a-50875c57e91c)

**Comment by ChaosAlphard** [comment]
哈哈，我也想要这个😀

**Comment by gaboolic** [comment]
日期的有date  2024-05-09
datetime 2024-05-09 18:57:40
N开头的 有点像v模式下的日期模式：
二〇一三年十月初十  ，癸巳年（蛇）十月初十

算数模式的话，相当于用Lua写个计算器了，有点费劲啊

**Comment by ChaosAlphard** [comment]
我写了一个，不过不能用小键盘输入+-*/  还没搞明白原因_(:з」∠)_
![图片](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/724bf8b1-1ccf-4118-8c83-70e958175b62)
![图片](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/bed71b88-a50f-40c9-bab2-92d04b184f7f)

**Comment by ChaosAlphard** [comment]
> 日期的有date 2024-05-09 datetime 2024-05-09 18:57:40 N开头的 有点像v模式下的日期模式： N20131112 二〇一三年十月初十 ，癸巳年（蛇）十月初十
> 
> 算数模式的话，相当于用Lua写个计算器了，有点费劲啊

偷懒一点可以直接用pcall(load())

**Comment by gaboolic** [comment]
很好啊可以合过来
小键盘貌似是rimelib版本问题



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月9日(Thu) Evening10:19
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gaboolic/rime-shuangpin-fuzhuma] 【需求】能不能加个类似于搜狗的v模式，算式和日期模式 (Issue #26)




 
我写了一个，不过不能用小键盘输入+-*/  还没搞明白原因_(:з」∠)_
 default.png (view on web)
 default.png (view on web)

**Comment by ChihoiTse** [comment]
> 日期的有date 2024-05-09 datetime 2024-05-09 18:57:40 N开头的 有点像v模式下的日期模式： N20131112 二〇一三年十月初十 ，癸巳年（蛇）十月初十
> 
> 算数模式的话，相当于用Lua写个计算器了，有点费劲啊

这个日期模式并不是date 的 2024/05/09，而是输入任意一个日期，自动生成对应的内容，你看图片我输入的是2013年

**Comment by ChihoiTse** [comment]
老哥提交一下pr呗哈哈哈，我也想用，v模式算数很经常用，可以直接明了的把算数过程给别人看

**Comment by ChaosAlphard** [comment]
现在这个要用math.cos(90)才有结果，我再改改 改成直接输cos(90)这种 _(:з」∠)_

**Comment by ChihoiTse** [comment]
膜拜大佬哈哈哈哈，坐等更新

**Comment by ChaosAlphard** [comment]
头疼，之前还好好的，结果不知道动到哪了，导致build出来的文件里面一直没有引用我写的那个lua脚本，唉开摆，周末再看什么问题_(:з」∠)_
![图片](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/2a98534a-308f-4121-ad28-4ee537a3d487)

**Comment by gaboolic** [comment]
> > 日期的有date 2024-05-09 datetime 2024-05-09 18:57:40 N开头的 有点像v模式下的日期模式： N20131112 二〇一三年十月初十 ，癸巳年（蛇）十月初十
> > 算数模式的话，相当于用Lua写个计算器了，有点费劲啊
> 
> 这个日期模式并不是date 的 2024/05/09，而是输入任意一个日期，自动生成对应的内容，你看图片我输入的是2013年

N 模式可以输入，N20131112 二〇一三年十月初十 ，癸巳年（蛇）十月初十   ，只不过只有这2种格式

**Comment by ChaosAlphard** [comment]
摸鱼的时候把剩下的弄完了，这一版比较简单，高级功能后续有时间再弄，pr已经提了，没问题的话等合并了

**Comment by gaboolic** [comment]
老哥，N 模式可以输入，N20131112 二〇一三年十月初十 ，癸巳年（蛇）十月初十 ，只不过只有这2种格式
你如果方便 可以再加第三种 公历年月日的，来pr啊，你就可以自动当贡献者了

**Comment by gaboolic** [comment]
老哥，来群里玩696353204

**Comment by gaboolic** [comment]
老哥们强 完美解决
