### ISSUE TITLE
【需求】emoji候选放在候选页的最后，靠前的位置留给文字候选

### ISSUE THREAD

**Issue by ChaosAlphard** [gaboolic/rime-shuangpin-fuzhuma#29]
emoji使用频率没有文字高，但是会出现在2-4候选这种靠前的位置，感不合理，建议降低排序权重，让emoji始终出现在靠后的位置
举例：
实际情况↓　　　　　　　　　　期望情况↓
![图片](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/a7cc0557-b35a-4cc6-9fe4-f1a249ca41e1)![图片](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/26186575/a954c887-6b2d-455c-94dd-773d9ea83eac)

**Comment by ChihoiTse** [comment]
怎么我的没有emoji出来的，怎么开的这个配置
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/e3aa4b61-5135-4503-a27f-930ef386e8bb)

**Comment by gaboolic** [comment]
> 怎么我的没有emoji出来的，怎么开的这个配置 ![image](https://private-user-images.githubusercontent.com/49972747/329199627-e3aa4b61-5135-4503-a27f-930ef386e8bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTI3NDMsIm5iZiI6MTcxNTI1MjQ0MywicGF0aCI6Ii80OTk3Mjc0Ny8zMjkxOTk2MjctZTNhYTRiNjEtNTEzNS00NTAzLWEyN2YtOTMwZWYzODZlOGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDExMDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYWE0ZTEwYzBkYzljYjEzMjJkNmQyMjM2MTAyMmIzZTBjYjY3Yzg0ZmM0Njc1ZTRhMGFhNmFiNzM5OGIwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qq4AuEYXW6J41J3VFVcG_R3Aqv3qXDDA8-L6b8cFvK8)

有个开关的，你按ctrl+` 开启emoji就有了

**Comment by gaboolic** [comment]
这个默认是出现在文字的第二行
如果想降低权重 得搞个Lua，不过难度也不大

**Comment by gaboolic** [comment]
好像有人实现了
https://github.com/iDvel/rime-ice/issues/770

**Comment by gaboolic** [comment]
其实我有点倾向于 不让opencc出emoji
需要打emoji的时候 用ae引导一下，例如aeyezi 出现的就是叶子和椰子的emoji

**Comment by ChihoiTse** [comment]
`ae`引导怎么打开？我在配置文件里面没有看到有ae引导的功能诶

**Comment by gaboolic** [comment]
> `ae`引导怎么打开？我在配置文件里面没有看到有ae引导的功能诶

之前删了 改成了opencc自动出，
现在我也感觉opencc自动出不太方便
还是加上ae引导，想打再打，一会再加回来

**Comment by gaboolic** [comment]
我加了ae模式
不过这个emoji的词库 没双拼
是支持英文、全拼，后面等我有空了 派生一个双拼的

☀ sunny;tian'qi`weather

**Comment by ChihoiTse** [comment]
期待双拼版本

**Comment by ChaosAlphard** [comment]
> 好像有人实现了 [iDvel/rime-ice#770](https://github.com/iDvel/rime-ice/issues/770)

不错，我先抄过来用着😀

**Comment by ChihoiTse** [comment]
> > 好像有人实现了 [iDvel/rime-ice#770](https://github.com/iDvel/rime-ice/issues/770)
> 
> 不错，我先抄过来用着😀

抄完pr一份给我呗[rime-shuangpin-fuzhuma](https://github.com/ChihoiTse/rime-shuangpin-fuzhuma)，我用的`lakuhana`分支

**Comment by gaboolic** [comment]
xdm，我建了q群696353204 来玩

**Comment by suibianzai** [comment]
> emoji使用频率没有文字高，但是会出现在2-4候选这种靠前的位置，感不合理，建议降低排序权重，让emoji始终出现在靠后的位置 举例： 实际情况↓　　　　　　　　　　期望情况↓ ![图片](https://private-user-images.githubusercontent.com/26186575/329186391-a7cc0557-b35a-4cc6-9fe4-f1a249ca41e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTYwMzgsIm5iZiI6MTcxNjUxNTczOCwicGF0aCI6Ii8yNjE4NjU3NS8zMjkxODYzOTEtYTdjYzA1NTctYjM1YS00Y2M2LTlmZTQtZjFhMjQ5Y2E0MWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxNTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNmEyY2UzYmRlNWE1NmRiNzdlMzExY2Y3ZjlmN2JiYWE2Mzk1YTZiYjhmYjRiYmZlNWFjMDYwOWJkZjFlY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ER9eiDoE6IAtX77sBlLodKeNaINzI9fE-HdY9wQe-WY)![图片](https://private-user-images.githubusercontent.com/26186575/329186802-a954c887-6b2d-455c-94dd-773d9ea83eac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTYwMzgsIm5iZiI6MTcxNjUxNTczOCwicGF0aCI6Ii8yNjE4NjU3NS8zMjkxODY4MDItYTk1NGM4ODctNmIyZC00NTVjLTk0ZGQtNzczZDllYTgzZWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxNTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNDRmZTNkYmFmZmI5YzY3NjEwMDQ0ODc5ZTEyNDlkZjRjZDUyMDNhYzU5MjBlYWUyNjU5NzQxMjcxMzllNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3tttSJJDMYLwhmxdoESV_zORAMlEUl-ytd-VRUS6EuA)

你好 我想请问怎么开启emoji功能啊？
