### ISSUE TITLE
如何不显示形码

### ISSUE THREAD

**Issue by lingmacker** [gaboolic/rime-shuangpin-fuzhuma#3]
如何不显示形码ni
<img width="546" alt="image" src="https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/32018160/72f2a72f-a3e3-42e9-8ad1-08b373914893">

**Comment by gaboolic** [comment]
translator:
  dictionary: flypy_flypy.extended
  enable_completion: false
  ##  默认为不超过 2 个字的候选项显示输入码；将 2 改为 0 可关闭编码提示，
  ##  改为 1 则是只显示单字的输入码，依此类推。
  translator/spelling_hints: 2

**Comment by gaboolic** [comment]
https://github.com/gaboolic/rime-shuangpin-fuzhuma/issues/4#issue-2241877293
