### ISSUE TITLE
请教一下如何让程序自动调整词序

### ISSUE THREAD

**Issue by GrandmaChen** [gaboolic/rime-shuangpin-fuzhuma#42]
比如输入zd时，“再”字永远在“在”字前，不论打多少遍“在”都排第二

**Comment by gaboolic** [comment]
z是在&nbsp; zd首选是再
这个置顶了
另外非置顶的话 可以看issue faq 打开自动调频


来群里玩啊 696353204



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月11日(Sat) AM10:37
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gaboolic/rime-shuangpin-fuzhuma] 请教一下如何让程序自动调整词序 (Issue #42)




 
比如输入zd时，“再”字永远在“在”字前，不论打多少遍“在”都排第二
