### ISSUE TITLE
tab 直接引导辅助码选项失灵

### ISSUE THREAD

**Issue by transread** [gaboolic/rime-shuangpin-fuzhuma#49]
最新方案中，如下功能失灵：

bindings:
   - { when: composing, accept: Tab, send: '[' } ## 取消注释后：tab引导辅助码

取消 # 后，按tab键只会输出"["。

![PixPin_2024-05-15_21-30-20](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/8240676/f37a8b1e-5560-44c3-b0fc-19a1b15007e7)

相反，添加 #，反而能够实现用tab直接引导辅助码功能

**Comment by lakuhana** [comment]
`{ when: composing, accept: Tab, send: '[' } ` 就是当输入tab时，输出`[`，把tab绑定到`[`，而`[`本身就是用于引导辅助码的

**Comment by transread** [comment]
哦，那就是我弄混了。我来关闭问题。

**Comment by transread** [comment]
那就是我记忆错乱了，此问题可以关闭了
