### ISSUE TITLE
请问如何通过长按空格进行定位修改功能？

### ISSUE THREAD

**Issue by transread** [gaboolic/rime-shuangpin-fuzhuma#5]
在影子输入法中，可以通过 长按空格 + 输入 a-z 选择指定候选词、并进行修改，请问如何在 rime 中实现这个功能？

![v2-b532b8c91e26a2e1d5fbdd2d4510be29_b](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/8240676/de0f5ede-4878-4de8-af1f-f091c65ff090)

**Comment by gaboolic** [comment]
rime中是按‘tab’

**Comment by transread** [comment]
但是无法实现长按tab键，按照现在的状态，长按tab，光标会快速移动，无法实现通过a、b、c 指定候选词、并在候选词后面添加辅助码。

其实您这个方案已经很好了，我有这个想法是看到 影子输入法 有这个功能，感觉能够提高效率，好奇rime能不能实现

**Comment by transread** [comment]
我不会编程，下面是刚刚用Kimi得出的结果，不知道对不对

在 Rime 输入法中实现长按空格显示 a, b, c, d 并根据选择定位到相应汉字拼音末尾的功能，需要结合 Rime 的按键绑定和 Lua 脚本功能。以下是一个可能的实现方案：

### 1. 编辑 Rime 配置文件

打开 `default.yaml` 或 `user.yaml` 配置文件，添加或修改 `key_binder` 部分来定义长按空格键的行为。

```yaml
key_binder:
  '<space>': { long_pressing: true, actions: ["show_pinyin_selector"] }
```

这里定义了长按空格键时执行 `show_pinyin_selector` 动作。

### 2. 编写 Lua 脚本来处理选择

在 Rime 的 `scripts` 目录下创建一个新的 Lua 脚本文件，例如 `pinyin_selector.lua`，并编写以下代码：

```lua
-- pinyin_selector.lua
local function on_key_press(key, event)
  if event == "press" and key == "space" then
    -- 显示 a, b, c, d 选择器
    rime.show候选("a", "b", "c", "d")
  end
end

local function on_choiceemade(choice)
  if choice then
    -- 根据选择的字母定位到相应的拼音
    local pinyin = "输入的拼音字符串"
    local cursor_pos = get_cursor_pos()
    -- 这里需要根据 a, b, c, d 的选择来计算光标应该定位到的位置
    -- 例如，可以使用 string.find 或类似的方法来定位
    local new_cursor_pos = cursor_pos + 1 -- 根据实际情况调整
    set_cursor_pos(new_cursor_pos)
  end
end

return {
  on_key_press = on_key_press,
  on_choiceemade = on_choiceemade
}
```

在这个 Lua 脚本中，我们定义了两个函数：`on_key_press` 用于在长按空格时显示选择器，`on_choiceemade` 用于在选择后定位光标。你需要根据实际情况调整代码，特别是光标定位的逻辑。

### 3. 在配置文件中引用 Lua 脚本

在 `default.yaml` 或 `user.yaml` 配置文件中，引用刚才编写的 Lua 脚本：

```yaml
patch:
  "engine/lua_script": {
    "scripts": ["pinyin_selector"]
  }
```

**Comment by gaboolic** [comment]
lua固然是可以的，但是我感觉用组合键是不是也行

**Comment by gaboolic** [comment]
key_binder:
  import_preset: default
  bindings:
    #- { when: composing, accept: Tab, send: '[' } ## 取消注释后：tab引导辅助码
    - { when: composing, accept: Control+m, send: Return }
    - { when: composing, accept: Control+w, send: Control+BackSpace }
    - { when: has_menu, accept: semicolon, send: 2 }
    - { when: has_menu, accept: slash, send: 3 }
    - { when: composing, accept: Control+i, send: Shift+Right }
    - { when: composing, accept: Control+o, send: Shift+Left }
    ## 对以下4行取消注释后：启用光标回退至特定音节后、补充辅助码的功能
    ## （自然码等其他双拼用户请在 pinyin_switch.yaml 中设置）
    #- { when: composing, accept: Control+1, send_sequence: '{Home}{Shift+Right}[' }
    #- { when: composing, accept: Control+2, send_sequence: '{Home}{Shift+Right}{Shift+Right}[' }
    #- { when: composing, accept: Control+3, send_sequence: '{Home}{Shift+Right}{Shift+Right}{Shift+Right}[' }
    #- { when: composing, accept: Control+4, send_sequence: '{Home}{Shift+Right}{Shift+Right}{Shift+Right}{Shift+Right}[' }



你看下被注释的部分，你打开试试。是Control+1 Control+2，你改成Tab+a Tab+b

**Comment by transread** [comment]
Tab+a Tab+b，不行啊

我把 Control+1 Control+2 依次设定为  Control+a、s、d、z、x、c 了 ［抚额笑］

**Comment by gaboolic** [comment]
那估计Tab+a的组合键在rime上不支持 Control+a能用就好
