### ISSUE TITLE
每次更新之后都要重调一遍设置，请问该怎么解决？

### ISSUE THREAD

**Issue by transread** [gaboolic/rime-shuangpin-fuzhuma#54]
每次更新之后都要重调一遍设置，请问该怎么解决？

**Comment by gaboolic** [comment]
你说的设置 是中英文 繁简 emoji开关那些吗
据说用ctrl+`打开菜单去调整可以记忆

**Comment by lakuhana** [comment]
你是说配置冲突的话，可以把自己的配置写到custom.yaml里面。如果是置顶词或者别的，也是可以自己创建一个自己的配置

**Comment by suibianzai** [comment]
把所有自己的配置另外写在.custom.yaml的补丁文件里，每次更新文件后重新部署，补丁就会重新打上去。
原理参考：https://blog.csdn.net/weixin_42148809/article/details/124827354
