### ISSUE TITLE
求教如何用 aeiou 选词，感觉用数字比较麻烦

### ISSUE THREAD

**Issue by transread** [gaboolic/rime-shuangpin-fuzhuma#6]
![PixPin_2024-04-15_08-55-01](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/8240676/f064baa7-0ea3-42d0-96fb-1e197b7ac9ea)

**Comment by gaboolic** [comment]
不行的，aeiou同时也是韵母，没法做到选词
你用过哪个方案是aeiou选词吗？声笔 也是aeiou追加笔画 顶功的吧

**Comment by gaboolic** [comment]
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/3831173/2acfbabb-9378-4db8-98e2-019fbf137fb3)
