### ISSUE TITLE
【需求】有没有会的教一下我怎么把`/`模式引导修改'F'引导

### ISSUE THREAD

**Issue by lakuhana** [gaboolic/rime-shuangpin-fuzhuma#60]
现在`/`模式是这样的
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/4dc77e91-8589-4067-ad73-4ad2e26ee33e)
![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/49972747/926c1dba-a6f5-497f-82a9-ff64be7584c6)
但是这样/就没办法自动上屏了，我想要/自动上屏，把/引导改为F引导，比如 `F1`  `Ffh` 这样子， 自己改过，但是不起效果，不知道哪里漏了配置没改

**Comment by gaboolic** [comment]
最开始尝试过V，没成功，后来发现用/也挺好
等待有缘人解答
