### ISSUE TITLE
TODO内的英文模糊输入的lua怎么没了

### ISSUE THREAD

**Issue by Anber55** [gaboolic/rime-shuangpin-fuzhuma#67]
大佬，还会做这个lua吗？一直在关注

**Comment by gaboolic** [comment]
用拼写规则实现了
aw beul
<img width="188" alt="image" src="https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/3831173/c70cec00-14ff-4c51-ab04-b92be28ffe08">

**Comment by Anber55** [comment]
我刚才进行了尝试，多添加了几个，结果就这几个添加好了进行部署的时候，Squirrel内存一下子到了2、3个g，简直带不动

、、、
    - derive/^(\w).+(\w)$/$1$2/
    - derive/^(\w).+(\w)(\w)$/$1$2$3/
    - derive/^(\w).+(\w)(\w)(\w)$/$1$2$3$4/
    - derive/^(\w).+(\w)(\w)(\w)(\w)$/$1$2$3$4$5/
    - derive/^(\w)(\w).+(\w)$/$1$2$3/
    - derive/^(\w)(\w).+(\w)(\w)$/$1$2$3$4/
、、、

**Comment by gaboolic** [comment]
感觉前后各2码足够实用了

**Comment by lingmacker** [comment]
这个怎么启用啊？

**Comment by gaboolic** [comment]
已经是默认启用的，比如beautiful，输入aw然后beul即可
