### ISSUE TITLE
🙋‍♂️请问可以打出繁体中文吗？

### ISSUE THREAD

**Issue by trevim99** [gaboolic/rime-shuangpin-fuzhuma#68]
大佬， 
请问可以改配置打出繁体中文吗？
谢谢 🙏🙏🙏

**Comment by gaboolic** [comment]
默认就能打繁体的单字
也提供了opencc的简繁切换开关

**Comment by trevim99** [comment]
谢谢您👍👍
请问要如何叫出 简繁切换开关 和 只出现 繁体中文的 侯选字框？ 😂🤣

（请参考图， 谢谢）

🙏🙏🙏

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/138210045/5f874f9c-7bb0-45b4-94c9-67e28cb10971)

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/138210045/5cbc86fb-a3e3-4c21-b695-6bf3bfa2df8b)

**Comment by trevim99** [comment]
謝謝您🙏🙏🙏， 我找到簡繁的開關了😊😊
大佬的配置非常好， 謝謝👍👍

**Comment by gaboolic** [comment]
好的，菜单在有的输入法比如fcitx上面就有可视化的，
也可以 ctrl + ` 呼出菜单

**Comment by trevim99** [comment]
> 好的，菜单在有的输入法比如fcitx上面就有可视化的， 也可以 ctrl + ` 呼出菜单

谢谢您🙏🙏🙏

🙋‍♂️请问预设值可以设成繁体中文吗❓
要改那个档案？
谢谢指导😊



![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/138210045/8624c0e9-4a18-4544-8c0b-a20c3b5f176e)

**Comment by gaboolic** [comment]
其实只要呼出菜单选一次 它就记住了。改的话是moqi.yaml
`
switches_engine:  
  switches:
    - name: ascii_mode
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: traditionalization
      states: [ 简, 繁 ]
    - name: emoji
      states: [ 💀, 😄 ]
    - name: chaifen
      states: [ 不拆, 扌斥 ]
    - name: mars
      reset: 0
      states: [ 地, 煋 ] #火星文
    - name: ascii_punct
      states: [ 。，, ．， ]
`
你参考火星文加reset: 1
也就是
`
    - name: traditionalization
      states: [ 简, 繁 ]
       reset: 1
`
不过加了reset，就不会记忆菜单的选择了，永远默认繁体

**Comment by trevim99** [comment]
謝謝您😊， 我再試試
剛接觸小狼毫及小鶴雙拼，
一切都還在熟悉中😁

多謝指點🙏🙏🙏

**Comment by trevim99** [comment]
您好



🙋‍♂️我在Android的手機（Gboard小鶴雙拼輸入法的預設碼表）羽=YV， 需=WV
，我希望能把 【鶴形+小鶴雙拼 方案】的 羽=YU ，  需=XU（及同音字）也改成 羽=YV， 需=WV（及同音字）， 
請問有機會修改嗎？請問要改那個檔案呢 ？


多謝指點 🙏🙏🙏

![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/138210045/8f247b57-4143-40be-9b0e-a076d3150696)



![image](https://github.com/gaboolic/rime-shuangpin-fuzhuma/assets/138210045/1de61d14-408d-438a-8121-cd2361aa6d1d)

**Comment by gaboolic** [comment]
在你的方案中找到    # - derive/^([jqxy])u/$1v/ # 开启jv=ju的模式
去掉#

**Comment by trevim99** [comment]
😁謝謝大佬， 經指導已成功開啓 开启jv=ju的模式， 謝謝
🙏🙏🙏
