### ISSUE TITLE
reverse_moqima 词库编译时产生大量 invalid entry definition

### ISSUE THREAD

**Issue by EtaoinWu** [gaboolic/rime-shuangpin-fuzhuma#69]
作者您好！非常感谢您设计的这套输入方案。我发现该方案在初次编译、构建 `reverse_moqima` 词库时，会有大量的形如

```plain
W20240702 16:12:16.466304 30644 entry_collector.cc:179] invalid entry definition at #80375.
```

的错误，最后这个数字从 `#1` 一直增长到八万多。经观察发现 `reverse_moqima.dict.yaml` 中每个字定义形如

```plain
吖	kzya	口丫
```

我猜测其第三列，rime 觉得它应该填一个词频，但是词库中实际上提供的是拆分？

**Comment by gaboolic** [comment]
感谢反馈，我没注意到日志的错误
后续修改下

**Comment by gaboolic** [comment]
加上了columns:
  - text
  - code
  - comment
应该好了

**Comment by EtaoinWu** [comment]
fixed by a3a619b
