### ISSUE TITLE
建议拆分出一个单独的自动上屏版

### ISSUE THREAD

**Issue by sf467** [gaboolic/rime-shuangpin-fuzhuma#78]
自动上屏版，类似小鹤音形的音形码模式，目前本项目的自动上屏版还是有一些可以改善的地方
1. 自动上屏版主要是单字输入为主，不需要极大的词库，过大的词库反而会妨碍单字自动上屏，可以将 cn_dicts_moqi/word.dict.yaml 中大量诸如 “啊嗷	aaao” “阿波	aabo” 之类的词删去，仅保留部分高频词，其他的词库文件也需要更改
2. 作为四码定长方案，自动上屏版依赖肌肉记忆，而这个项目曾经多次更改其词频，这增加了学习难度，可以单独维护，或者拆分出来一份专门的自动上屏的墨奇音形rime配置文件，不更改词频，也删去一些诸如智能模型的功能

**Comment by gaboolic** [comment]
可以拆出来

不过第一点，诸如 “啊嗷 aaao” “阿波 aabo” 之类的词 实际上也没有单字，我生成码表的时候 是计算过的，没有单字码都会生成
第二点的话，改词频之后 重新运行脚本才会重新生成自动上屏的码表

**Comment by sf467** [comment]
> 可以拆出来
> 
> 不过第一点，诸如 “啊嗷 aaao” “阿波 aabo” 之类的词 实际上也没有单字，我生成码表的时候 是计算过的，没有单字码都会生成 第二点的话，改词频之后 重新运行脚本才会重新生成自动上屏的码表

有些低频词确实会影响单字的自动上屏，甚至在默认情况下，这些词在候选栏中的位置要在所需的单字之前
![Screenshot_2024-07-23-12-24-12-88_97a2b898327add53e982bbebadc3de52](https://github.com/user-attachments/assets/3cd03122-4acd-408f-b679-f311b90cb8b9)

**Comment by sf467** [comment]
![Screenshot_2024-07-23-12-29-54-23_a87fd7db6caa850b517aa6fa9d2fcd0e](https://github.com/user-attachments/assets/bf93aa5c-a8e2-4399-9448-9a221669fa1c)

这种改变

**Comment by gaboolic** [comment]
“有些低频词确实会影响单字的自动上屏，甚至在默认情况下，这些词在候选栏中的位置要在所需的单字之前”
这种情况确实不好处理，我想到的简单点的方式是看频率，如果词的频率比如说小于500啥的，就不要了

码表改变：确实改变过，最开始是用的雾凇拼音的频率，后来我发现不太合适，重算了一个白霜拼音，型打单比形更多，比如创新型 实用型，形一般组词
不过以后 码表基本上稳定了，我后来加上细胞词库重算，单字的顺序几乎没变

**Comment by sf467** [comment]
> “有些低频词确实会影响单字的自动上屏，甚至在默认情况下，这些词在候选栏中的位置要在所需的单字之前” 这种情况确实不好处理，我想到的简单点的方式是看频率，如果词的频率比如说小于500啥的，就不要了
> 
> 码表改变：确实改变过，最开始是用的雾凇拼音的频率，后来我发现不太合适，重算了一个白霜拼音，型打单比形更多，比如创新型 实用型，形一般组词 不过以后 码表基本上稳定了，我后来加上细胞词库重算，单字的顺序几乎没变

卡频率我觉得确实是一种办法，标准可以再高一点，音形码只需要一个精简的词库就行。因为给出的是一个精练的词库文件，所以用户自己修改起来也就方便多了。
这几天一直在不停的改词，一遇到有冲突的无意义词就去文件里删，真的删不完。而且因为词库文件那个符号我手机上打不出来，如果是在手机打字的过程中遇到，还得把它记下来，在电脑上改（）
或者能不能直接把小鹤的二字词拿过来，再改成墨奇码？

**Comment by gaboolic** [comment]
小鹤的二字词 词频不是很好，比如bu xiu，小鹤是“补休”，理论上应该是“不朽”
官鹤的词库也经常被吐槽 还不能修改
其实你可以fork一个，然后改成自己的码表，一人一码表

**Comment by gaboolic** [comment]
福都	fu dou	7
封君	feng jun	185
聚生	ju sheng	13
图说	tu shuo	225
十盆	shi pen	3

看上去是可以去掉词频<100的词，“图说”词频高是因为是百度的一个app

**Comment by gaboolic** [comment]
下次 我再重新生成一下 去掉词频过低的

**Comment by gaboolic** [comment]
对了，在自动上屏版中，注释掉long_word_filter就可以  fgjy 先是凤 第二个是封君了
