### ISSUE TITLE
无法输入辅助码

### ISSUE THREAD

**Issue by hcwanz** [gaboolic/rime-shuangpin-fuzhuma#79]
![image](https://github.com/user-attachments/assets/45ee9754-740d-4e68-9ec8-cda695bdbb1e) 
![image](https://github.com/user-attachments/assets/ccc6e404-bc37-4765-b4f7-d55608d00514) 
![image](https://github.com/user-attachments/assets/db353f60-e992-4fd3-8b94-2ac87e4fd4a2)

**Comment by gaboolic** [comment]
再输入/即可字词分离
https://moqiyinxing.chunqiujinjing.com/index/mo-qi-yin-xing-gao-ji-gong-neng/shi-yong-zi-ci-fen-li
