### ISSUE TITLE
我只想用双拼加辅助码，那其他的那些拆字的配置文件是不是可以不更新，或者删了，不影响吧

### ISSUE THREAD

**Issue by verve91** [gaboolic/rime-shuangpin-fuzhuma#8]

**Comment by verve91** [comment]
我看了看配置文件，用得到的不能删

**Comment by gaboolic** [comment]
应该删了不影响双拼+辅助码
比如拆字的文件，删了只是不能用az 去组字了

**Comment by verve91** [comment]
嗷嗷嗷，好嘞，我不懂这些，

**Comment by verve91** [comment]
还有，作者大大，下次如果再更新了小鹤的方案，可不可以把加入或者删了哪些功能在readme里面说一下，这样我知道该改哪里😂

**Comment by gaboolic** [comment]
今天是应一些用户要求 加了数字大写 农历 ，模糊音的注释啥的
如果你觉得用不到 其实可以一直用之前的版本，只更新词库文件就行了
另外 如果你需要自定义一些东西并且想和这个仓库同步的话，可以把自定义的东西放flypy_flypy.custom.yaml 这样就不冲突了

**Comment by verve91** [comment]
好嘞，收到
