### ISSUE TITLE
请问能开启easy-en输入方案吗

### ISSUE THREAD

**Issue by corwin1949** [gaboolic/rime-shuangpin-fuzhuma#81]
1. 请问能开启easy-en输入方案吗，我看到有相关文件但我试了下，无法开启这个输入方案。

2. 我用小鹤音形，好像没法混合输入英语单词，请问是我设置错误，还是本来就无法混合输入。（可以用aw模式输入，话说是否会考虑在aw中支持easy-en呢）

您的项目对我非常有用，感谢。

**Comment by gaboolic** [comment]
aw中用的就是easy-en吧？
默认模式只能打中文，没有加英文的翻译器

**Comment by corwin1949** [comment]
> aw中用的就是easy-en吧？ 默认模式只能打中文，没有加英文的翻译器

啊，我研究下。可能配置的时候搞坏了。
