### ISSUE TITLE
自然码方案全拼预览问题

### ISSUE THREAD

**Issue by dustnova** [gaboolic/rime-shuangpin-fuzhuma#82]
自然码方案的拼音预览是小鹤双拼的，有些错误。
![image](https://github.com/user-attachments/assets/c6783f46-d5f5-41ec-bb3c-51aec17629be)

**Comment by gaboolic** [comment]
下次改下

**Comment by gaboolic** [comment]
为每个双拼都做输入预览太复杂了，
还是直接看原始编码吧😂
