### ISSUE TITLE
`rime-flypy-flypy.zip` 中缺少 `cn_dicts_cell/` 目录

### ISSUE THREAD

**Issue by CarameowCookie** [gaboolic/rime-shuangpin-fuzhuma#83]
https://github.com/gaboolic/rime-shuangpin-fuzhuma/releases/download/0.0.10/rime-flypy-flypy.zip

这个 ZIP 文件缺少了 `cn_dicts_cell/` 目录及其内容，导致无法在 `flypy_flypy.extended.dict.yaml` 中启用 `cn_dicts_cell/` 的细胞词库。

**Comment by gaboolic** [comment]
cn_dicts_cell原有的细胞词库，没有辅助码部分。

可以用最新的moqi_wan_flypy.schema.yaml 方案（不过还没release）
