### ISSUE TITLE
关于模糊音

### ISSUE THREAD

**Issue by enoch1937** [gaboolic/rime-shuangpin-fuzhuma#9]
我中文拼音不好，但也认为花精力重新学习标准发音可能没必要，
一直以来都需要借助模糊音来输入，有没有可能添加韵母的模糊音功能。我自己有尝试过你声母模糊音的写法，但是没实现。

**Comment by gaboolic** [comment]
添加韵母的话，和这个类似
- derive/^z([a-z])/v$1/ 
- derive/^v([a-z])/z$1/ 

比如添加in和ing的模糊音，如果in是n，ing是k的话，可以这样：
- derive/^([a-z])n/$1k/
- derive/^([a-z])k/$1n/

**Comment by gaboolic** [comment]
https://github.com/gaboolic/rime-shuangpin-fuzhuma/issues/4#issuecomment-2064022545
