### ISSUE TITLE
三码Tab上屏词部分和显示不符

### ISSUE THREAD

**Issue by Jinlixian** [gaboolic/rime-shuangpin-fuzhuma#90]
我用的moqi_zrm方案，tab上屏词部分和实际词汇不一样。比如zrm：’自然码‘，显示的是’自然‘，上屏的却是正确的，比如zzp-走资派，提示的是‘最早’。

**Comment by Jinlixian** [comment]
![WX20240828-225904@2x](https://github.com/user-attachments/assets/6a7d8114-7939-462b-9176-806fb0ef5a6b)

**Comment by gaboolic** [comment]
这和空码有关系，zzp在自然码里面空码了
如果有zzp的码，就正常了
