### ISSUE TITLE
🙋‍♂️請問（ 0.0.10  版本）ac引導 【自造詞】及 自訂的 加字加詞 能換行嗎？ 怎麼設置？ 謝謝

### ISSUE THREAD

**Issue by trevim99** [gaboolic/rime-shuangpin-fuzhuma#92]
🙋‍♂️請問 0.0.10  版本

 1. 請問ac引導 【自造詞】 在那個檔案設置？能提供範例參考？ 

<img width="921" alt="ac" src="https://github.com/user-attachments/assets/54f2e62b-5cd5-48b2-b646-2b2cb19b3b4f">

 2. 請問 自訂的 加字加詞 能換行嗎？ 怎麼設置？ 謝謝

<img width="814" alt="ruhedrhhPixPin_2024-09-01_03-05-24" src="https://github.com/user-attachments/assets/14ceb167-43f5-4e30-96a9-b5d605151d3a">

🙏🙏🙏

**Comment by gaboolic** [comment]
输入ac之后直接正常打词就行了，然后下次就能记住。
customphrase.txt里面可以加<br>换行
需要把moqi.yaml里面
#- lua_filter@*laneChangeAndSpace_Filter   # 把<br>替换为换行
这一行前面的#去掉
