### ISSUE TITLE
用户词频开关问题

### ISSUE THREAD

**Issue by houzixiashanxiedaima** [gaboolic/rime-shuangpin-fuzhuma#93]
我想要开启自己的用户词频，但是看`FAQ`中是说要在对应的配置文件中开启`enable_user_dict: true`，这样每次更新的话，会被覆盖更新，请问有什么`PATCH`的形式吗？

**Comment by gaboolic** [comment]
应该是这样吧 可以看下官方文档
```
patch:
  translator/enable_user_dict: true
```

**Comment by gaboolic** [comment]
是的，只要开了用户词库 词频就会变。
所以我做了一个“ac”开启造词的功能，这样造的词会一直在最后
也有一个“禁用某些pattern的用户词库”选项，不过这需要你自己配置了

**Comment by gaboolic** [comment]
呃，我又仔细看了一下你说的 "我的需求应该是不固定词频，并非要使用用户词库"
你是想调频的同时 不记忆新词？这我不了解怎么实现，目前rime就是靠用户词库来实现的调频

**Comment by houzixiashanxiedaima** [comment]
举个例子：我现在打「de」，排在第一的一直是「得」，我想根据我选中的次数，把「的」排到第一；
我已经成功开启了用户词频（我经常选的字上面会有*号），但是我经常选的字，还是不会排到第一，请问是词频「优先级」不够吗？

**Comment by gaboolic** [comment]
得 的 地的问题，是出简让全
d是的，de就让给了“得”
同样的，q是去，qu就让给了“区”
这个在custom_phrase.txt里面，是置顶的，你可以修改

**Comment by houzixiashanxiedaima** [comment]
好的，非常感谢耐心解答，祝您生活愉快！👍
