### ISSUE TITLE
【bug】主分支最新版 ac 自造词模式失效

### ISSUE THREAD

**Issue by expoli** [gaboolic/rime-shuangpin-fuzhuma#97]
https://github.com/user-attachments/assets/419ad640-a6e5-42af-807d-eaa5acdd5e1a

**Comment by expoli** [comment]
![Screenshot_2024-09-24-12-48-14-66_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/user-attachments/assets/b58ac8a7-f80a-43f5-b6fb-238e761ba05d)

自然码双拼自然码方案自造词无法使用

**Comment by gaboolic** [comment]
修改了
