### ISSUE TITLE
简纯皮肤，在中文模式下，有以下问题

### ISSUE THREAD

**Issue by xqhjay** [gaboolic/rime-shuangpin-fuzhuma#98]
1，逗号，句号，分号，反引号，需要按空格键才能上屏。
2，长按shif键，锁定后，输入大写字母不会显示在输入码上，并且也需要按空格键才能上屏

**Comment by gaboolic** [comment]
我刚尝试了一下，没有遇到 符号按空格才能上屏的问题

**Comment by xqhjay** [comment]
> 我刚尝试了一下，没有遇到 符号按空格才能上屏的问题

同样的皮肤, 我从同文3.30正式版换成最新nightly版就正常了。好奇两个版本按键的 text 或者 commit 的处理机制发生了变化吗？或者punctuator的半角一项里，是否加上commit也有影响呢

**Comment by gaboolic** [comment]
那就不知道了，得问同文了😂
